In [116]:
# V4-01 — imports, paths, load structural base (output_from_linking.csv)

from __future__ import annotations

import pathlib
import re

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

ROOT = pathlib.Path("/Users/davekokel/Projects/carp_v2").resolve()
BASE = ROOT / "seed_kits" / "legacy_wrangling_v2" / "working"

STRUCT_PATH = BASE / "output_from_linking.csv"

print("ROOT:       ", ROOT)
print("STRUCT_PATH:", STRUCT_PATH)

if not STRUCT_PATH.exists():
    raise FileNotFoundError(f"Structural CSV not found at {STRUCT_PATH}")

# ---------------------------------------------------------------------
# Load structural base (one row per ROI)
# ---------------------------------------------------------------------

df_struct = pd.read_csv(STRUCT_PATH)

print("V4-01 — df_struct shape:", df_struct.shape)
print("V4-01 — df_struct columns:")
print(list(df_struct.columns))

print("\nV4-01 — sample rows:")
display(df_struct.head(5))

ROOT:        /Users/davekokel/Projects/carp_v2
STRUCT_PATH: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/working/output_from_linking.csv
V4-01 — df_struct shape: (869, 41)
V4-01 — df_struct columns:
['date_experiment', 'fish', 'roi_rel', 'roi_name', 'roi_tiffs', 'roi_dir', 'dataset', 'dataset_slug_raw', 'dataset_slug_norm', 'roi_path_date_yyyymmdd', 'experiment_folder', 'fish_folder', 'roi_folder', 'fish_number', 'fish_id', 'fish_age_token', 'fish_age_hpf', 'roi_index_token', 'roi_index', 'fish_nickname', 'roi_anatomy_tokens', 'roi_anatomy', 'dataset_slug', 'sheet_slug_norm', 'date_mount_yyyymmdd', 'Data location', 'ZF female genotype', 'ZF male genotype', 'additional plasmids injected', 'additional mRNAs injected', 'additonal proteins injected', 'additonal dye and chemicals', 'link_source', 'plate_date', 'mount_id_inferred', 'mount_id_source', 'plate_key', 'plate_id_filled', 'slot_id_filled', 'roi_index_within_slot', 'bruker_roi_id']

V4-01 — sample rows:

,date_experiment,fish,roi_rel,roi_name,roi_tiffs,roi_dir,dataset,dataset_slug_raw,dataset_slug_norm,roi_path_date_yyyymmdd,...,additonal dye and chemicals,link_source,plate_date,mount_id_inferred,mount_id_source,plate_key,plate_id_filled,slot_id_filled,roi_index_within_slot,bruker_roi_id
0,20250428_mem_histone,fish1_72hpf,roi1_tail,roi1_tail,3206.0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,korra,korra,korra,20250428,...,NaN,inferred,20250428,1,inferred,20250428::20250428_mem_histone::1,1,1,1,20250428-plate1-slot1-roi1
1,20250428_mem_histone,fish1_72hpf,roi2_hindbrain_spine,roi2_hindbrain_spine,9760.0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,korra,korra,korra,20250428,...,NaN,inferred,20250428,1,inferred,20250428::20250428_mem_histone::1,1,1,2,20250428-plate1-slot1-roi2
2,20250429_mem_cytosol,fish1_24hpf,roi1,roi1,6873.0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,korra,korra,korra,20250429,...,NaN,inferred,20250429,1,inferred,20250429::20250429_mem_cytosol::1,2,1,1,20250429-plate2-slot1-roi1
3,20250429_mem_cytosol,fish1_24hpf,roi1_test,roi1_test,46.0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,korra,korra,korra,20250429,...,NaN,inferred,20250429,1,inferred,20250429::20250429_mem_cytosol::1,2,1,2,20250429-plate2-slot1-roi2
4,20250429_mem_cytosol,fish2_48hpf,roi1,roi1,3180.0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,korra,korra,korra,20250429,...,NaN,inferred,20250429,1,inferred,20250429::20250429_mem_cytosol::1,2,2,1,20250429-plate2-slot2-roi1

In [117]:
# V4-02 — load parent-name catalog and construct / marker catalogs (correct paths)

RAW_V2 = ROOT / "seed_kits" / "legacy_wrangling_v2" / "raw"
STD    = ROOT / "seed_kits" / "2025-11-15-121231-autoload"

PARENT_MAP_PATH = RAW_V2 / "Unique_parent_names__mom_dad_combined__preview_dqm.xlsx"
CONSTRUCTS_PATH = STD / "constructs_plasmid.csv"
FLUORS_PATH     = STD / "fluors.csv"
TAGS_PATH       = STD / "tags.xlsx"

print("PARENT_MAP_PATH:", PARENT_MAP_PATH)
print("CONSTRUCTS_PATH:", CONSTRUCTS_PATH)
print("FLUORS_PATH:    ", FLUORS_PATH)
print("TAGS_PATH:      ", TAGS_PATH)

for p in [PARENT_MAP_PATH, CONSTRUCTS_PATH, FLUORS_PATH, TAGS_PATH]:
    if not p.exists():
        print("MISSING:", p)

# ---------------------------------------------------------------------
# Load each catalog
# ---------------------------------------------------------------------

parent_map = pd.read_excel(PARENT_MAP_PATH)
constructs = pd.read_csv(CONSTRUCTS_PATH)
fluors     = pd.read_csv(FLUORS_PATH)
tags       = pd.read_excel(TAGS_PATH)

print("\nV4-02 — parent_map shape:", parent_map.shape)
print("V4-02 — constructs shape:", constructs.shape)
print("V4-02 — fluors shape:   ", fluors.shape)
print("V4-02 — tags shape:     ", tags.shape)

print("\nV4-02 — parent_map columns:")
print(list(parent_map.columns))

print("\nV4-02 — constructs columns:")
print(list(constructs.columns))

print("\nV4-02 — fluors columns:")
print(list(fluors.columns))

print("\nV4-02 — tags columns:")
print(list(tags.columns))

print("\nV4-02 — parent_map head:")
display(parent_map.head(5))

PARENT_MAP_PATH: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/raw/Unique_parent_names__mom_dad_combined__preview_dqm.xlsx
CONSTRUCTS_PATH: /Users/davekokel/Projects/carp_v2/seed_kits/2025-11-15-121231-autoload/constructs_plasmid.csv
FLUORS_PATH:     /Users/davekokel/Projects/carp_v2/seed_kits/2025-11-15-121231-autoload/fluors.csv
TAGS_PATH:       /Users/davekokel/Projects/carp_v2/seed_kits/2025-11-15-121231-autoload/tags.xlsx

V4-02 — parent_map shape: (41, 5)
V4-02 — constructs shape: (286, 12)
V4-02 — fluors shape:    (28, 5)
V4-02 — tags shape:      (10, 5)

V4-02 — parent_map columns:
['parent_fish_name', 'plasmid_base_code', 'allele', 'injected_rna', 'injected_plasmid']

V4-02 — constructs columns:
['plasmid_code', 'plasmid_name', 'plasmid_nickname', 'resistance', 'plasmid_notes', 'used_for_injection_plasmid', 'used_for_injection_rna', 'used_for_injection_crispr', 'n_fluors_per_plasmid', 'fluor_code', 'tag_code', 'tag_pos']

V4-02 — fluors columns:
['nickname', 'excitation_nm', 'emission_nm', 'note', 'aliases']

V4-02 — tags columns:
['nickname', 'localization', 'note', 'citation_link', 'aliases']

V4-02 — parent_map head:

,parent_fish_name,plasmid_base_code,allele,injected_rna,injected_plasmid
0,tandem mem:mStayGold,pDQM005,301,NaN,NaN
1,ef1a:2xLynk:tdmSG(J) (F1 of allele 302),pDQM005,302,NaN,NaN
2,casper/rnf,NaN,NaN,NaN,NaN
3,ef1a:2xLynk:tdmChilada (F1 of allele 315),pDQM082,315,NaN,NaN
4,tdmScarlet3S2 (F1 of allele 325),pDQM136,325,NaN,NaN

In [118]:
# V4-03 — map ZF female/male genotypes to parent_map and build genotype / treatment codes

import pandas as pd
import numpy as np
import re

df_enrich = df_struct.copy()

# ---------------------------------------------------------------------
# Check we have the ZF genotype columns
# ---------------------------------------------------------------------

expected_parent_cols = ["ZF female genotype", "ZF male genotype"]
missing_parent_cols = [c for c in expected_parent_cols if c not in df_enrich.columns]
if missing_parent_cols:
    raise KeyError(f"df_struct is missing expected ZF genotype columns: {missing_parent_cols}")

print("V4-03 — starting enrichment from ZF genotype columns")
print("  df_enrich rows:", len(df_enrich))
print("  df_enrich columns:", len(df_enrich.columns))

# ---------------------------------------------------------------------
# Normalize parent-name strings
# ---------------------------------------------------------------------

def norm_name(s):
    if pd.isna(s):
        return None
    t = str(s).strip().lower()
    t = re.sub(r"\s+", " ", t)
    return t or None

df_enrich["parent_female_name"] = df_enrich["ZF female genotype"]
df_enrich["parent_male_name"]   = df_enrich["ZF male genotype"]

df_enrich["parent_female_norm"] = df_enrich["parent_female_name"].apply(norm_name)
df_enrich["parent_male_norm"]   = df_enrich["parent_male_name"].apply(norm_name)

print("\nV4-03 — sample normalized parent names from df_enrich:")
display(
    df_enrich[
        ["parent_female_name", "parent_female_norm",
         "parent_male_name", "parent_male_norm"]
    ].drop_duplicates().head(20)
)

# ---------------------------------------------------------------------
# Normalize parent_map catalog
# ---------------------------------------------------------------------

parent_map_norm = parent_map.copy()
parent_map_norm["parent_name_norm"] = parent_map_norm["parent_fish_name"].apply(norm_name)

pm_cols = [
    "parent_name_norm",
    "plasmid_base_code",
    "allele",
    "injected_rna",
    "injected_plasmid",
]
pm_small = parent_map_norm[pm_cols].copy()

# ---------------------------------------------------------------------
# Pipe-splitting helpers
# ---------------------------------------------------------------------

def split_pipe(val):
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return []
    s = str(val).strip()
    if not s:
        return []
    return [x.strip() for x in s.split("|") if x.strip()]

def join_unique(items):
    out = []
    seen = set()
    for x in items:
        if x is None:
            continue
        sx = str(x).strip()
        if not sx:
            continue
        if sx not in seen:
            seen.add(sx)
            out.append(sx)
    return "|".join(out) if out else None

# ---------------------------------------------------------------------
# Merge parent_map for female and male parents
# ---------------------------------------------------------------------

df_enrich = df_enrich.merge(
    pm_small.add_prefix("female_"),
    left_on="parent_female_norm",
    right_on="female_parent_name_norm",
    how="left",
)

df_enrich = df_enrich.merge(
    pm_small.add_prefix("male_"),
    left_on="parent_male_norm",
    right_on="male_parent_name_norm",
    how="left",
)

print("\nV4-03 — after merging parent_map:")
print("  columns:", len(df_enrich.columns))

# ---------------------------------------------------------------------
# Build genotype_base_codes and genotype_allele_codes
# ---------------------------------------------------------------------

def combine_parent_codes(row, which):
    """
    which = 'plasmid' or 'allele'
    """
    if which == "plasmid":
        fem = row.get("female_plasmid_base_code")
        mal = row.get("male_plasmid_base_code")
    elif which == "allele":
        fem = row.get("female_allele")
        mal = row.get("male_allele")
    else:
        return None

    items = split_pipe(fem) + split_pipe(mal)
    return join_unique(items)

df_enrich["genotype_base_codes"]   = df_enrich.apply(lambda r: combine_parent_codes(r, "plasmid"), axis=1)
df_enrich["genotype_allele_codes"] = df_enrich.apply(lambda r: combine_parent_codes(r, "allele"), axis=1)

# ---------------------------------------------------------------------
# Build treatment_plasmid_base_codes / treatment_rna_base_codes
# ---------------------------------------------------------------------

def combine_treatment_codes(row, which):
    if which == "plasmid":
        fem = row.get("female_injected_plasmid")
        mal = row.get("male_injected_plasmid")
    elif which == "rna":
        fem = row.get("female_injected_rna")
        mal = row.get("male_injected_rna")
    else:
        return None

    items = split_pipe(fem) + split_pipe(mal)
    return join_unique(items)

df_enrich["treatment_plasmid_base_codes"] = df_enrich.apply(
    lambda r: combine_treatment_codes(r, "plasmid"), axis=1
)
df_enrich["treatment_rna_base_codes"] = df_enrich.apply(
    lambda r: combine_treatment_codes(r, "rna"), axis=1
)

# ---------------------------------------------------------------------
# QC: coverage and sample rows
# ---------------------------------------------------------------------

has_geno = df_enrich["genotype_base_codes"].notna()
n_with_geno = has_geno.sum()

print("\nV4-03 — genotype coverage:")
print("  rows with genotype_base_codes:", n_with_geno, "/", len(df_enrich))

print("\nV4-03 — sample rows with genotype_base_codes:")
display(
    df_enrich.loc[has_geno, [
        "roi_dir",
        "parent_female_name",
        "parent_male_name",
        "genotype_base_codes",
        "genotype_allele_codes",
        "treatment_plasmid_base_codes",
        "treatment_rna_base_codes",
    ]].head(20)
)

print("\nV4-03 — sample rows with NO genotype_base_codes (for inspection):")
display(
    df_enrich.loc[~has_geno, [
        "roi_dir",
        "parent_female_name",
        "parent_male_name",
    ]].head(20)
)

V4-03 — starting enrichment from ZF genotype columns
  df_enrich rows: 869
  df_enrich columns: 41

V4-03 — sample normalized parent names from df_enrich:

,parent_female_name,parent_female_norm,parent_male_name,parent_male_norm
0,NaN,None,NaN,None
66,Ben (F2 of allele 310),ben (f2 of allele 310),Abe (F2 of allele 309),abe (f2 of allele 309)
76,Jim (F2 of allele 316),jim (f2 of allele 316),Ben (F2 of allele 310),ben (f2 of allele 310)

V4-03 — after merging parent_map:
  columns: 55

V4-03 — genotype coverage:
  rows with genotype_base_codes: 16 / 869

V4-03 — sample rows with genotype_base_codes:

,roi_dir,parent_female_name,parent_male_name,genotype_base_codes,genotype_allele_codes,treatment_plasmid_base_codes,treatment_rna_base_codes
66,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
67,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
68,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
69,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
70,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
71,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
72,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
73,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
74,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
75,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Ben (F2 of allele 310),Abe (F2 of allele 309),pDQM034,310|309,None,None
76,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Jim (F2 of allele 316),Ben (F2 of allele 310),pDQM059|pDQM034,316|310,None,None
77,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Jim (F2 of allele 316),Ben (F2 of allele 310),pDQM059|pDQM034,316|310,None,None
78,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Jim (F2 of allele 316),Ben (F2 of allele 310),pDQM059|pDQM034,316|310,None,None
79,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Jim (F2 of allele 316),Ben (F2 of allele 310),pDQM059|pDQM034,316|310,None,None
80,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Jim (F2 of allele 316),Ben (F2 of allele 310),pDQM059|pDQM034,316|310,None,None
81,/clusterfs/vast/abcabc/Korra_Foundation/202506...,Jim (F2 of allele 316),Ben (F2 of allele 310),pDQM059|pDQM034,316|310,None,None

V4-03 — sample rows with NO genotype_base_codes (for inspection):

,roi_dir,parent_female_name,parent_male_name
0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
1,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
2,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
3,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
4,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
5,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
6,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
7,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
8,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
9,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN
10,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
11,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
12,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
13,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
14,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
15,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
16,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
17,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
18,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN
19,/clusterfs/vast/abcabc/Korra_Foundation/202505...,NaN,NaN

In [119]:
# V4-04 — attach constructs/fluors/tags and build genotype marker/localization columns

import pandas as pd
import numpy as np

print("V4-04 — starting from df_enrich shape:", df_enrich.shape)

# ---------------------------------------------------------------------
# 1) Normalize constructs, fluors, tags
# ---------------------------------------------------------------------

# constructs: we have plasmid_code, fluor_code, tag_code, tag_pos
constructs_small = constructs[[
    "plasmid_code",
    "fluor_code",
    "tag_code",
    "tag_pos",
]].copy()

print("V4-04 — constructs_small sample:")
display(constructs_small.head(10))

# fluors.csv: columns = nickname, excitation_nm, emission_nm, note, aliases
# There is no explicit fluor_code column; we assume constructs.fluor_code == fluors.nickname
fluors_small = fluors.rename(columns={"nickname": "fluor_code"})
fluors_small = fluors_small[[
    "fluor_code",
    "excitation_nm",
    "emission_nm",
    "note",
    "aliases",
]].copy()

print("\nV4-04 — fluors_small sample:")
display(fluors_small.head(10))

# tags.xlsx: columns = nickname, localization, note, citation_link, aliases
# Assume constructs.tag_code == tags.nickname
tags_small = tags.rename(columns={"nickname": "tag_code", "localization": "tag_localization"})
tags_small = tags_small[[
    "tag_code",
    "tag_localization",
    "note",
    "citation_link",
    "aliases",
]].copy()

print("\nV4-04 — tags_small sample:")
display(tags_small.head(10))

# QC: fluor_code coverage
fluor_codes_constructs = set(constructs_small["fluor_code"].dropna().unique())
fluor_codes_catalog    = set(fluors_small["fluor_code"].dropna().unique())
missing_fluors = sorted(fluor_codes_constructs - fluor_codes_catalog)
print("\nV4-04 — unique fluor_codes in constructs:", len(fluor_codes_constructs))
print("V4-04 — unique fluor_codes in fluors:    ", len(fluor_codes_catalog))
print("V4-04 — fluor_codes in constructs but not in fluors:", missing_fluors[:20])

# QC: tag_code coverage
tag_codes_constructs = set(constructs_small["tag_code"].dropna().unique())
tag_codes_catalog    = set(tags_small["tag_code"].dropna().unique())
missing_tags = sorted(tag_codes_constructs - tag_codes_catalog)
print("\nV4-04 — unique tag_codes in constructs:", len(tag_codes_constructs))
print("V4-04 — unique tag_codes in tags:      ", len(tag_codes_catalog))
print("V4-04 — tag_codes in constructs but not in tags:", missing_tags[:20])

# ---------------------------------------------------------------------
# 2) Build per-plasmid marker metadata
# ---------------------------------------------------------------------

# Join constructs -> fluors
constructs_f = constructs_small.merge(
    fluors_small,
    on="fluor_code",
    how="left",
    suffixes=("", "_fluor"),
)

# Join constructs_f -> tags
constructs_ft = constructs_f.merge(
    tags_small,
    on="tag_code",
    how="left",
    suffixes=("", "_tag"),
)

print("\nV4-04 — constructs_ft (per plasmid marker info) sample:")
display(constructs_ft.head(15))

# ---------------------------------------------------------------------
# 3) Expand genotype_base_codes per ROI into rows and join marker info
# ---------------------------------------------------------------------

# Only rows with genotype_base_codes
geno = df_enrich[["roi_dir", "genotype_base_codes"]].dropna().copy()
geno["plasmid_code"] = geno["genotype_base_codes"].apply(lambda s: split_pipe(s))
geno = geno.explode("plasmid_code").reset_index(drop=True)

print("\nV4-04 — geno (exploded genotype_base_codes) sample:")
display(geno.head(15))

# Join with constructs_ft to attach fluor, tag, localization per (ROI, plasmid)
geno_markers = geno.merge(
    constructs_ft,
    on="plasmid_code",
    how="left",
)

print("\nV4-04 — geno_markers sample:")
display(
    geno_markers[
        ["roi_dir", "plasmid_code", "fluor_code", "tag_code", "tag_localization", "tag_pos"]
    ].head(20)
)

# ---------------------------------------------------------------------
# 4) Aggregate marker info back to per-ROI columns
# ---------------------------------------------------------------------

def agg_marker_lists(subdf):
    fluor_codes = join_unique(subdf["fluor_code"].tolist())
    tag_codes   = join_unique(subdf["tag_code"].tolist())
    locs        = join_unique(subdf["tag_localization"].tolist())

    # fusion label: "fluor_code::tag_code"
    # if either side is missing, skip that combo
    fusion_labels = []
    for fc, tc in zip(subdf["fluor_code"], subdf["tag_code"]):
        if pd.isna(fc) or pd.isna(tc):
            continue
        fusion_labels.append(f"{fc}::{tc}")
    fusion_labels = join_unique(fusion_labels)

    # fluor(localization) combos: "fluor_code(localization)"
    fluor_org = []
    for fc, loc in zip(subdf["fluor_code"], subdf["tag_localization"]):
        if pd.isna(fc) or pd.isna(loc):
            continue
        fluor_org.append(f"{fc}({loc})")
    fluor_org = join_unique(fluor_org)

    return pd.Series({
        "genotype_marker_fluor_codes": fluor_codes,
        "genotype_marker_tag_codes": tag_codes,
        "genotype_marker_localizations": locs,
        "genotype_marker_fusion_labels": fusion_labels,
        "all_unique_organelles": locs,          # for now: genotype-only organelles
        "all_fluor_organelles": fluor_org,      # genotype-only for now
    })

geno_agg = (
    geno_markers
    .groupby("roi_dir", dropna=False)
    .apply(agg_marker_lists)
    .reset_index()
)

print("\nV4-04 — geno_agg (per-ROI marker rollup) sample:")
display(geno_agg.head(20))

# ---------------------------------------------------------------------
# 5) Merge marker rollup back into df_enrich
# ---------------------------------------------------------------------

before_cols = set(df_enrich.columns)

df_enrich = df_enrich.merge(
    geno_agg,
    on="roi_dir",
    how="left",
)

after_cols = set(df_enrich.columns)
new_cols = sorted(after_cols - before_cols)

print("\nV4-04 — df_enrich after merging marker rollup:")
print("  shape:", df_enrich.shape)
print("  new marker columns:", new_cols)

# QC: sample enriched rows
print("\nV4-04 — sample enriched rows (with marker columns):")
display(
    df_enrich.loc[
        df_enrich["genotype_marker_fluor_codes"].notna(),
        [
            "roi_dir",
            "genotype_base_codes",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "genotype_marker_localizations",
            "genotype_marker_fusion_labels",
            "all_unique_organelles",
            "all_fluor_organelles",
        ],
    ].head(20)
)

V4-04 — starting from df_enrich shape: (869, 59)
V4-04 — constructs_small sample:

  plasmid_code fluor_code tag_code tag_pos
0      pDQM001        mSG      NaN     NaN
1      pDQM002        mSG      NaN     NaN
2      pDQM005      tdmSG   2xLynk       N
3      pDQM006      tdmSG      NaN     NaN
4      pDQM007      tdmSG      NaN     NaN
5      pDQM008      tdmSG      NaN     NaN
6      pDQM009   mScarlet      NaN     NaN
7      pDQM009     mKate2      NaN     NaN
8      pDQM009   Electra2      NaN     NaN
9      pDQM009       mKOK      NaN     NaN

V4-04 — fluors_small sample:

  fluor_code  excitation_nm  emission_nm  note  aliases
0  E2Crimson          611.0        646.0   NaN      NaN
1   Electra2          503.0        516.0   NaN      NaN
2        GFP          488.0        510.0   NaN      NaN
3    mBaoJin          500.0        508.0   NaN      NaN
4     mBeRFP          446.0        611.0   NaN      NaN
5  mCardinal          604.0        659.0   NaN      NaN
6   mChilada          587.0        610.0   NaN      NaN
7   mCitrine          516.0        529.0   NaN      NaN
8    mGold2s          517.0        529.0   NaN      NaN
9    mGold2t          515.0        527.0   NaN      NaN

V4-04 — tags_small sample:

,tag_code,tag_localization,note,citation_link,aliases
0,2Xcox8A,mitochondria,NaN,NaN,NaN
1,2xLynk,membrane,double lyn kinase domain which directs the flu...,NaN,NaN
2,DHB,cell cycle,DHB contains a dominant nuclear localization s...,https://pmc.ncbi.nlm.nih.gov/articles/PMC8716472/,NaN
3,sec61b,ER,NaN,NaN,NaN
4,LAMP1,lysosome,NaN,NaN,NaN
5,lifeact,actin,NaN,https://www.nature.com/articles/nmeth.1220,NaN
6,H2B,histone,NaN,NaN,NaN
7,pcna,nucleus,NaN,NaN,NaN
8,GMN,NaN,NaN,NaN,NaN
9,CDT1,NaN,NaN,NaN,NaN

V4-04 — unique fluor_codes in constructs: 33
V4-04 — unique fluor_codes in fluors:     27
V4-04 — fluor_codes in constructs but not in fluors: ['Halo', 'gfp', 'mKoK', 'mSG', 'mYH', 'mchilada', 'tdmSG', 'tdmSc3S2', 'tdmYH']

V4-04 — unique tag_codes in constructs: 12
V4-04 — unique tag_codes in tags:       10
V4-04 — tag_codes in constructs but not in tags: ['dhb', 'h2b']

V4-04 — constructs_ft (per plasmid marker info) sample:

,plasmid_code,fluor_code,tag_code,tag_pos,excitation_nm,emission_nm,note,aliases,tag_localization,note_tag,citation_link,aliases_tag
0,pDQM001,mSG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pDQM002,mSG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pDQM005,tdmSG,2xLynk,N,NaN,NaN,NaN,NaN,membrane,double lyn kinase domain which directs the flu...,NaN,NaN
3,pDQM006,tdmSG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pDQM007,tdmSG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,pDQM008,tdmSG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,pDQM009,mScarlet,NaN,NaN,569.0,594.0,NaN,NaN,NaN,NaN,NaN,NaN
7,pDQM009,mKate2,NaN,NaN,588.0,633.0,NaN,NaN,NaN,NaN,NaN,NaN
8,pDQM009,Electra2,NaN,NaN,503.0,516.0,NaN,NaN,NaN,NaN,NaN,NaN
9,pDQM009,mKOK,NaN,NaN,588.0,633.0,NaN,NaN,NaN,NaN,NaN,NaN
10,pDQM009,mTFP1,NaN,NaN,462.0,492.0,NaN,NaN,NaN,NaN,NaN,NaN
11,pDQM010,mScarlet,NaN,NaN,569.0,594.0,NaN,NaN,NaN,NaN,NaN,NaN
12,pDQM010,mKate2,NaN,NaN,588.0,633.0,NaN,NaN,NaN,NaN,NaN,NaN
13,pDQM010,Electra2,NaN,NaN,503.0,516.0,NaN,NaN,NaN,NaN,NaN,NaN
14,pDQM010,mKOK,NaN,NaN,588.0,633.0,NaN,NaN,NaN,NaN,NaN,NaN

V4-04 — geno (exploded genotype_base_codes) sample:

,roi_dir,genotype_base_codes,plasmid_code
0,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
1,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
2,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
3,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
4,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
5,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
6,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
7,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
8,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
9,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,pDQM034
10,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,pDQM059
11,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,pDQM034
12,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,pDQM059
13,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,pDQM034
14,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,pDQM059

V4-04 — geno_markers sample:

,roi_dir,plasmid_code,fluor_code,tag_code,tag_localization,tag_pos
0,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2,NaN,NaN,NaN
1,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mCitrine,NaN,NaN,NaN
2,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,Electra2,NaN,NaN,NaN
3,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKOK,NaN,NaN,NaN
4,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mTFP1,NaN,NaN,NaN
5,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2,NaN,NaN,NaN
6,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mCitrine,NaN,NaN,NaN
7,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,Electra2,NaN,NaN,NaN
8,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKOK,NaN,NaN,NaN
9,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mTFP1,NaN,NaN,NaN
10,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2,NaN,NaN,NaN
11,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mCitrine,NaN,NaN,NaN
12,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,Electra2,NaN,NaN,NaN
13,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKOK,NaN,NaN,NaN
14,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mTFP1,NaN,NaN,NaN
15,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2,NaN,NaN,NaN
16,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mCitrine,NaN,NaN,NaN
17,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,Electra2,NaN,NaN,NaN
18,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKOK,NaN,NaN,NaN
19,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mTFP1,NaN,NaN,NaN

V4-04 — geno_agg (per-ROI marker rollup) sample:

/var/folders/29/cdrb2nrn01s4d1_n6gvxy5j80000gn/T/ipykernel_53268/2958448772.py:154: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(agg_marker_lists)

,roi_dir,genotype_marker_fluor_codes,genotype_marker_tag_codes,genotype_marker_localizations,genotype_marker_fusion_labels,all_unique_organelles,all_fluor_organelles
0,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
1,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
2,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
3,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
4,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
5,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
6,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
7,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
8,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
9,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
10,/clusterfs/vast/abcabc/Korra_Foundation/202506...,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
11,/clusterfs/vast/abcabc/Korra_Foundation/202506...,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
12,/clusterfs/vast/abcabc/Korra_Foundation/202506...,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
13,/clusterfs/vast/abcabc/Korra_Foundation/202506...,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
14,/clusterfs/vast/abcabc/Korra_Foundation/202506...,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
15,/clusterfs/vast/abcabc/Korra_Foundation/202506...,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None

V4-04 — df_enrich after merging marker rollup:
  shape: (869, 65)
  new marker columns: ['all_fluor_organelles', 'all_unique_organelles', 'genotype_marker_fluor_codes', 'genotype_marker_fusion_labels', 'genotype_marker_localizations', 'genotype_marker_tag_codes']

V4-04 — sample enriched rows (with marker columns):

,roi_dir,genotype_base_codes,genotype_marker_fluor_codes,genotype_marker_tag_codes,genotype_marker_localizations,genotype_marker_fusion_labels,all_unique_organelles,all_fluor_organelles
66,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
67,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
68,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
69,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
70,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
71,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
72,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
73,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
74,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
75,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM034,mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
76,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
77,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
78,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
79,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
80,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None
81,/clusterfs/vast/abcabc/Korra_Foundation/202506...,pDQM059|pDQM034,gfp|mKate2|mCitrine|Electra2|mKOK|mTFP1,nan,nan,None,nan,None

In [120]:
# V4-04b — assign default "cytosol" tag/localization to untagged genotype markers

import numpy as np
import pandas as pd

print("V4-04b — initial organelle coverage (before cytosol default):")
print(df_enrich["all_unique_organelles"].notna().value_counts())

# mask: ROIs with genotype fluor markers but no tag/localization yet
mask_untagged = (
    df_enrich["genotype_marker_fluor_codes"].notna()
    & df_enrich["genotype_marker_tag_codes"].isna()
    & df_enrich["genotype_marker_localizations"].isna()
)

n_untagged = mask_untagged.sum()
print("V4-04b — ROIs with fluor but no tag/localization:", n_untagged)

# 1) set default tag/localization
df_enrich.loc[mask_untagged, "genotype_marker_tag_codes"] = "cytosol"
df_enrich.loc[mask_untagged, "genotype_marker_localizations"] = "cytosol"

# 2) ensure all_unique_organelles includes 'cytosol'
def add_cytosol(orgs):
    if pd.isna(orgs) or not str(orgs).strip():
        return "cytosol"
    toks = [t.strip() for t in str(orgs).split("|") if t.strip()]
    if "cytosol" in toks:
        return orgs
    return orgs + "|cytosol"

df_enrich.loc[mask_untagged, "all_unique_organelles"] = df_enrich.loc[
    mask_untagged, "all_unique_organelles"
].apply(add_cytosol)

# 3) ensure all_fluor_organelles includes fluor_code(cytosol)
def add_cytosol_fluor_org(row):
    org = row["all_fluor_organelles"]
    fl  = row["genotype_marker_fluor_codes"]
    if pd.isna(fl) or not str(fl).strip():
        return org

    # genotype_marker_fluor_codes may be pipe-separated
    fcodes = [t.strip() for t in str(fl).split("|") if t.strip()]
    new_tokens = [f"{fc}(cytosol)" for fc in fcodes]

    if pd.isna(org) or not str(org).strip():
        return "|".join(new_tokens)

    toks = [t.strip() for t in str(org).split("|") if t.strip()]
    existing = set(toks)
    for nt in new_tokens:
        if nt not in existing:
            toks.append(nt)
    return "|".join(toks)

df_enrich.loc[mask_untagged, "all_fluor_organelles"] = df_enrich.loc[
    mask_untagged
].apply(add_cytosol_fluor_org, axis=1)

print("\nV4-04b — organelle coverage AFTER cytosol default:")
print(df_enrich["all_unique_organelles"].notna().value_counts())

print("\nV4-04b — sample untagged (now cytosol) rows:")
display(
    df_enrich.loc[mask_untagged, [
        "roi_dir",
        "genotype_marker_fluor_codes",
        "genotype_marker_tag_codes",
        "genotype_marker_localizations",
        "all_unique_organelles",
        "all_fluor_organelles",
    ]].head(20)
)

V4-04b — initial organelle coverage (before cytosol default):
all_unique_organelles
False    853
True      16
Name: count, dtype: int64
V4-04b — ROIs with fluor but no tag/localization: 0

V4-04b — organelle coverage AFTER cytosol default:
all_unique_organelles
False    853
True      16
Name: count, dtype: int64

V4-04b — sample untagged (now cytosol) rows:

Empty DataFrame
Columns: [roi_dir, genotype_marker_fluor_codes, genotype_marker_tag_codes, genotype_marker_localizations, all_unique_organelles, all_fluor_organelles]
Index: []

In [121]:
# V4-04c — merge "additional injected" treatments from imaging_sheet without duplicating ROIs
#          and rename them to treatment_*_names_sheet

from pathlib import Path
import pandas as pd

RAW_V2 = ROOT / "seed_kits" / "legacy_wrangling_v2" / "raw"
IMAGING_SHEET_FILE = RAW_V2 / "2025-11-21-220012-imaging_sheet.xlsx"

print("V4-04c — imaging sheet file:", IMAGING_SHEET_FILE)
if not IMAGING_SHEET_FILE.exists():
    raise FileNotFoundError(f"Imaging sheet not found at {IMAGING_SHEET_FILE}")

df_imaging_sheet = pd.read_excel(IMAGING_SHEET_FILE)

print("V4-04c — df_imaging_sheet shape:", df_imaging_sheet.shape)
print("V4-04c — df_imaging_sheet columns:")
print(list(df_imaging_sheet.columns))

# Column names from the sheet (typos and all)
COL_DATA_LOCATION         = "Data location"
COL_ADD_PLASMIDS_INJECTED = "additional plasmids injected"
COL_ADD_MRNAS_INJECTED    = "additional mRNAs injected"
COL_ADD_PROTEINS_INJECTED = "additonal proteins injected"
COL_ADD_DYES_INJECTED     = "additonal dye and chemicals"

needed_cols = [
    COL_DATA_LOCATION,
    COL_ADD_PLASMIDS_INJECTED,
    COL_ADD_MRNAS_INJECTED,
    COL_ADD_PROTEINS_INJECTED,
    COL_ADD_DYES_INJECTED,
]

missing = [c for c in needed_cols if c not in df_imaging_sheet.columns]
if missing:
    print("V4-04c — WARNING: missing expected columns in imaging sheet:", missing)
    needed_cols = [c for c in needed_cols if c in df_imaging_sheet.columns]

sheet_small = df_imaging_sheet[needed_cols].copy()

def norm_path_str(s):
    if pd.isna(s):
        return None
    return str(s).strip().replace("\\", "/")

sheet_small["data_location_norm"] = sheet_small[COL_DATA_LOCATION].apply(norm_path_str)
df_enrich["data_location_norm"]   = df_enrich["Data location"].apply(norm_path_str)

print("\nV4-04c — nunique data_location_norm in sheet:", sheet_small["data_location_norm"].nunique())
print("V4-04c — nunique data_location_norm in df_enrich:", df_enrich["data_location_norm"].nunique())

# Aggregate to ONE ROW per data_location_norm so we don't duplicate ROIs
def agg_text(col):
    vals = [str(x).strip() for x in col.dropna() if str(x).strip()]
    if not vals:
        return None
    out = []
    seen = set()
    for v in vals:
        if v not in seen:
            seen.add(v)
            out.append(v)
    return "|".join(out)

group_cols = ["data_location_norm"]
agg_dict = {}

if COL_ADD_PLASMIDS_INJECTED in sheet_small.columns:
    agg_dict[COL_ADD_PLASMIDS_INJECTED] = agg_text
if COL_ADD_MRNAS_INJECTED in sheet_small.columns:
    agg_dict[COL_ADD_MRNAS_INJECTED]    = agg_text
if COL_ADD_PROTEINS_INJECTED in sheet_small.columns:
    agg_dict[COL_ADD_PROTEINS_INJECTED] = agg_text
if COL_ADD_DYES_INJECTED in sheet_small.columns:
    agg_dict[COL_ADD_DYES_INJECTED]     = agg_text

sheet_agg = (
    sheet_small
    .groupby(group_cols, dropna=True)
    .agg(agg_dict)
    .reset_index()
)

print("\nV4-04c — sheet_agg shape:", sheet_agg.shape)
print("V4-04c — sheet_agg sample:")
display(sheet_agg.head(20))

before_rows = len(df_enrich)
before_roi_unique = df_enrich["roi_dir"].nunique()
before_cols = set(df_enrich.columns)

df_enrich = df_enrich.merge(
    sheet_agg,
    on="data_location_norm",
    how="left",
    suffixes=("", "_sheet"),
)

after_rows = len(df_enrich)
after_roi_unique = df_enrich["roi_dir"].nunique()
after_cols = set(df_enrich.columns)

print("\nV4-04c — df_enrich after merge:")
print("  rows (before):", before_rows, "  rows (after):", after_rows)
print("  unique roi_dir (before):", before_roi_unique, "  (after):", after_roi_unique)
print("  new columns added:", sorted(after_cols - before_cols))

# Rename for clarity
rename_map = {}
if COL_ADD_PLASMIDS_INJECTED in df_enrich.columns:
    rename_map[COL_ADD_PLASMIDS_INJECTED] = "treatment_plasmid_names_sheet"
if COL_ADD_MRNAS_INJECTED in df_enrich.columns:
    rename_map[COL_ADD_MRNAS_INJECTED]    = "treatment_rna_names_sheet"
if COL_ADD_PROTEINS_INJECTED in df_enrich.columns:
    rename_map[COL_ADD_PROTEINS_INJECTED] = "treatment_protein_names_sheet"
if COL_ADD_DYES_INJECTED in df_enrich.columns:
    rename_map[COL_ADD_DYES_INJECTED]     = "treatment_dye_names_sheet"

df_enrich = df_enrich.rename(columns=rename_map)

print("\nV4-04c — sample enriched treatments from imaging sheet:")
cols_show = ["roi_dir", "Data location"]
cols_show += [c for c in [
    "treatment_plasmid_names_sheet",
    "treatment_rna_names_sheet",
    "treatment_protein_names_sheet",
    "treatment_dye_names_sheet",
] if c in df_enrich.columns]

display(df_enrich[cols_show].head(20))

# Also inspect the specific ROI we care about:
mask_0428 = df_enrich["roi_dir"].str.contains("20250428_mem_histone/fish1_72hpf/roi1_tail")
print("\nV4-04c — specific ROI row for 20250428_mem_histone/fish1_72hpf/roi1_tail:")
display(df_enrich.loc[mask_0428, cols_show])

V4-04c — imaging sheet file: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/raw/2025-11-21-220012-imaging_sheet.xlsx
V4-04c — df_imaging_sheet shape: (347, 28)
V4-04c — df_imaging_sheet columns:
['date_mount', 'mount_id', 'ZF female genotype', 'ZF male genotype', 'additional plasmids injected', 'additional mRNAs injected', 'additonal proteins injected', 'additonal dye and chemicals', 'Date born', 'Time mounted', 'Mounting Orientation', 'Date screened/Initial feedback', 'Date imaged', 'Time placed in scope', 'Start of imaging time', 'End of imaging time', 'Imaged Locations', 'Unique Targets with blanks', 'Unique Targets', 'Data location', 'Dataset size (GB) - raw data only', 'Camera Filters', 'JSON excite map for ZF male', 'JSON excite map for ZF female', 'JSON excite map for plasmid', 'JSON excite map for mRNA', 'comments', 'Data evaluation comments']

V4-04c — nunique data_location_norm in sheet: 225
V4-04c — nunique data_location_norm in df_enrich: 4

V4-04c — sheet_agg shape: (225, 5)
V4-04c — sheet_agg sample:

,data_location_norm,additional plasmids injected,additional mRNAs injected,additonal proteins injected,additonal dye and chemicals
0,9,None,2xCox8A:mScarlet3S2,None,None
1,U:/Data/20240911_Korra_Foundation/20250131_mem...,None,2xLynk:mSG; mYH:H2B,None,None
2,U:/Data/20240911_Korra_Foundation/20250131_mem...,None,2xLynk:mSG; mChilada:H2B,None,None
3,U:/Data/20240911_Korra_Foundation/20250204_mem...,None,mChilada:H2B (80 pg),None,None
4,U:/Data/20240911_Korra_Foundation/20250204_mem...,None,mYH:H2B (80 pg),None,None
5,U:/Data/20240911_Korra_Foundation/20250204_mem...,None,mYH:H2B (80 pg),None,None
6,U:/Data/20240911_Korra_Foundation/20250204_mem...,None,mYH:H2B (80 pg),None,None
7,U:/Data/20240911_Korra_Foundation/20250204_mem...,None,mYH:H2B (80 pg),None,None
8,U:/Data/20240911_Korra_Foundation/20250204_mem...,None,mYH:H2B (80 pg),None,None
9,U:/Data/20240911_Korra_Foundation/20250204_mem...,None,mYH:H2B (80 pg),None,None
10,U:/Data/20240911_Korra_Foundation/20250206_mem...,None,mChilada:H2B (80 pg),None,None
11,U:/Data/20240911_Korra_Foundation/20250206_mem...,None,mChilada:H2B (80 pg),None,None
12,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mYH:H2B (80 and 120 pg),None,None
13,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mChilada:H2B (80 and 120 pg),None,None
14,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mYH:H2B (80 and 120 pg),None,None
15,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mYH:H2B (80 and 120 pg),None,None
16,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mChilada:H2B (80 and 120 pg),None,None
17,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mYH:H2B (80 and 120 pg),None,None
18,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mYH:H2B (80 and 120 pg),None,None
19,U:/Data/20240911_Korra_Foundation/20250211_mem...,None,mYH:H2B (80 and 120 pg),None,None

V4-04c — df_enrich after merge:
  rows (before): 869   rows (after): 869
  unique roi_dir (before): 869   (after): 869
  new columns added: ['additional mRNAs injected_sheet', 'additional plasmids injected_sheet', 'additonal dye and chemicals_sheet', 'additonal proteins injected_sheet']

V4-04c — sample enriched treatments from imaging sheet:

,roi_dir,Data location,treatment_plasmid_names_sheet,treatment_rna_names_sheet,treatment_protein_names_sheet,treatment_dye_names_sheet
0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
1,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
2,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
3,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
4,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
5,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
6,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
7,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
8,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
9,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN
10,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
11,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
12,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
13,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
14,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
15,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
16,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
17,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
18,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN
19,/clusterfs/vast/abcabc/Korra_Foundation/202505...,X:\abcabc\Korra_Foundation\20250513_skittles(f...,NaN,phiC-NLS,NaN,NaN

V4-04c — specific ROI row for 20250428_mem_histone/fish1_72hpf/roi1_tail:

,roi_dir,Data location,treatment_plasmid_names_sheet,treatment_rna_names_sheet,treatment_protein_names_sheet,treatment_dye_names_sheet
0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,NaN,NaN,NaN,NaN,NaN

In [122]:
# V4-04d — promote untagged fluors to cytosol by default

# Assumes you already have constructs_ft like:
# constructs_ft columns:
# ['plasmid_code', 'fluor_code', 'tag_code', 'tag_pos',
#  'excitation_nm', 'emission_nm', 'note', 'aliases',
#  'tag_localization', 'note_tag', 'citation_link', 'aliases_tag']

print("V4-04d — before cytosol default:")
print("  total constructs_ft rows:", len(constructs_ft))
print("  rows with fluor_code but no tag_localization:",
      ((constructs_ft["fluor_code"].notna()) & (constructs_ft["tag_localization"].isna())).sum())

# define cytosol as the default organelle for untagged fluors
mask_untagged = constructs_ft["fluor_code"].notna() & constructs_ft["tag_localization"].isna()
constructs_ft.loc[mask_untagged, "tag_localization"] = "cytosol"

print("\nV4-04d — after cytosol default:")
print("  rows now tagged as cytosol:",
      (constructs_ft["tag_localization"] == "cytosol").sum())

print("\nV4-04d — sample constructs with cytosol localization:")
display(
    constructs_ft.loc[
        constructs_ft["tag_localization"] == "cytosol",
        ["plasmid_code", "fluor_code", "tag_code", "tag_pos", "tag_localization"]
    ].head(20)
)

V4-04d — before cytosol default:
  total constructs_ft rows: 291
  rows with fluor_code but no tag_localization: 192

V4-04d — after cytosol default:
  rows now tagged as cytosol: 192

V4-04d — sample constructs with cytosol localization:

   plasmid_code fluor_code tag_code tag_pos tag_localization
0       pDQM001        mSG      NaN     NaN          cytosol
1       pDQM002        mSG      NaN     NaN          cytosol
3       pDQM006      tdmSG      NaN     NaN          cytosol
4       pDQM007      tdmSG      NaN     NaN          cytosol
5       pDQM008      tdmSG      NaN     NaN          cytosol
6       pDQM009   mScarlet      NaN     NaN          cytosol
7       pDQM009     mKate2      NaN     NaN          cytosol
8       pDQM009   Electra2      NaN     NaN          cytosol
9       pDQM009       mKOK      NaN     NaN          cytosol
10      pDQM009      mTFP1      NaN     NaN          cytosol
11      pDQM010   mScarlet      NaN     NaN          cytosol
12      pDQM010     mKate2      NaN     NaN          cytosol
13      pDQM010   Electra2      NaN     NaN          cytosol
14      pDQM010       mKOK      NaN     NaN          cytosol
15      pDQM010      mTFP1      NaN     NaN          cytosol
16      pDQM011   Electra2      NaN     NaN          cytosol
17      pDQM012   Electra2      NaN     NaN          cytosol
18      pDQM013       mKOK      NaN     NaN          cytosol
19      pDQM014     mKate2      NaN     NaN          cytosol
20      pDQM015     mKate2      NaN     NaN          cytosol

In [124]:
# V4-04m — attach manual ROI mapping metadata (no genotype override yet)

from pathlib import Path
import pandas as pd

print("V4-04m — attaching manual ROI mapping metadata (no overrides)")

# Paths
MANUAL_PATH = ROOT / "seed_kits" / "legacy_wrangling_v2" / "raw" / "roi_missing_parents_for_manual_mapping_DQM_CNH (1).csv"
if not MANUAL_PATH.exists():
    raise FileNotFoundError(f"Manual ROI mapping sheet not found at {MANUAL_PATH}")

print("V4-04m — manual mapping sheet:", MANUAL_PATH)

manual = pd.read_csv(MANUAL_PATH)
print("V4-04m — manual sheet shape:", manual.shape)
print("V4-04m — manual sheet columns:", list(manual.columns))

# Normalize column names into a clean, namespaced set so we never fight suffixes
rename_map = {
    "slug": "manual_slug",
    "mother_fish_manual": "manual_mother_fish",
    "father_fish_manual": "manual_father_fish",
    "injection type": "manual_injection_type",
    "injection plasmid": "manual_injection_plasmid",
}
manual = manual.rename(columns=rename_map)

keep_cols = ["roi_dir"] + [c for c in rename_map.values() if c in manual.columns]

manual_small = manual[keep_cols].copy()
print("V4-04m — manual_small columns:", list(manual_small.columns))

before_rows = len(df_enrich)
before_rois = df_enrich["roi_dir"].nunique()

# Left join manual metadata onto df_enrich by roi_dir
df_enrich = df_enrich.merge(manual_small, on="roi_dir", how="left")

after_rows = len(df_enrich)
after_rois = df_enrich["roi_dir"].nunique()

print(f"V4-04m — df_enrich rows (before → after): {before_rows} → {after_rows}")
print(f"V4-04m — unique roi_dir (before → after): {before_rois} → {after_rois}")

# Quick sanity: how many ROIs picked up manual metadata?
meta_cols = [c for c in manual_small.columns if c != "roi_dir"]
if meta_cols:
    has_manual = df_enrich[meta_cols].notna().any(axis=1)
    print("V4-04m — ROIs with any manual metadata attached:", has_manual.sum())
    print("V4-04m — sample rows with manual metadata:")
    display(
        df_enrich.loc[has_manual, ["roi_dir"] + meta_cols].head(20)
    )
else:
    print("V4-04m — no manual_* columns present after rename; manual sheet is metadata-only and did not add fields.")

V4-04m — attaching manual ROI mapping metadata (no overrides)
V4-04m — manual mapping sheet: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/raw/roi_missing_parents_for_manual_mapping_DQM_CNH (1).csv
V4-04m — manual sheet shape: (172, 6)
V4-04m — manual sheet columns: ['roi_dir', 'slug', 'mother_fish_manual', 'father_fish_manual', 'injection type', 'injection plasmid']
V4-04m — manual_small columns: ['roi_dir', 'manual_slug', 'manual_mother_fish', 'manual_father_fish', 'manual_injection_type', 'manual_injection_plasmid']
V4-04m — df_enrich rows (before → after): 869 → 869
V4-04m — unique roi_dir (before → after): 869 → 869
V4-04m — ROIs with any manual metadata attached: 3
V4-04m — sample rows with manual metadata:

,roi_dir,manual_slug,manual_mother_fish,manual_father_fish,manual_injection_type,manual_injection_plasmid
44,/clusterfs/vast/abcabc/Korra_Foundation/202505...,skittlez,NaN,NaN,NaN,NaN
65,/clusterfs/vast/abcabc/Korra_Foundation/202506...,mitomSG,pDQM005(302),pDQM005(302),mRNA,MGCO-01
66,/clusterfs/vast/abcabc/Korra_Foundation/202506...,skittlez,NaN,NaN,NaN,NaN

In [125]:
# V4-04t — map treatment_rna_names_sheet and treatment_plasmid_names_sheet
#          to plasmid codes via Unique_injected_* mappers, then to marker fields

from pathlib import Path
import pandas as pd
import re

RAW_V2 = ROOT / "seed_kits" / "legacy_wrangling_v2" / "raw"

RNA_MAP_PATH      = RAW_V2 / "Unique_injected_rna__preview_dqm.xlsx"
PLASMID_MAP_PATH  = RAW_V2 / "Unique_injected_plasmid__preview_dqm.xlsx"

print("V4-04t — RNA map:", RNA_MAP_PATH)
print("V4-04t — plasmid map:", PLASMID_MAP_PATH)

if not RNA_MAP_PATH.exists():
    raise FileNotFoundError(f"RNA mapper not found at {RNA_MAP_PATH}")
if not PLASMID_MAP_PATH.exists():
    raise FileNotFoundError(f"Plasmid mapper not found at {PLASMID_MAP_PATH}")

rna_map     = pd.read_excel(RNA_MAP_PATH)
plasmid_map = pd.read_excel(PLASMID_MAP_PATH)

print("V4-04t — rna_map columns:", list(rna_map.columns))
print("V4-04t — plasmid_map columns:", list(plasmid_map.columns))

# expected columns (adjust if your actual names differ)
COL_RNA_NAME      = "injected_rna"
COL_RNA_PBASE     = "plasmid_base_code"

COL_PL_NAME       = "injected_plasmid"
COL_PL_PBASE      = "plasmid_base_code"

for c in [COL_RNA_NAME, COL_RNA_PBASE]:
    if c not in rna_map.columns:
        raise KeyError(f"RNA mapper missing column: {c}")
for c in [COL_PL_NAME, COL_PL_PBASE]:
    if c not in plasmid_map.columns:
        raise KeyError(f"Plasmid mapper missing column: {c}")

def norm_name(s):
    if pd.isna(s):
        return None
    t = str(s).strip()
    t = re.sub(r"\s+", " ", t)
    return t or None

rna_map["injected_rna_norm"]       = rna_map[COL_RNA_NAME].apply(norm_name)
plasmid_map["injected_plasmid_norm"] = plasmid_map[COL_PL_NAME].apply(norm_name)

# Prepare df_enrich treatment names
df_enrich["treatment_rna_names_norm"]      = df_enrich.get("treatment_rna_names_sheet", pd.Series(index=df_enrich.index)).apply(norm_name)
df_enrich["treatment_plasmid_names_norm"]  = df_enrich.get("treatment_plasmid_names_sheet", pd.Series(index=df_enrich.index)).apply(norm_name)

# helper: split pipe-separated names (from agg_text) into list
def split_pipe_or_single(s):
    if pd.isna(s):
        return []
    s = str(s).strip()
    if not s:
        return []
    return [x.strip() for x in s.split("|") if x.strip()]

# ── 1) explode treatment RNAs → map to plasmid_base_code ─────────────────────

df_trna = df_enrich[["roi_dir", "treatment_rna_names_sheet"]].dropna().copy()
df_trna["treatment_rna_token"] = df_trna["treatment_rna_names_sheet"].apply(split_pipe_or_single)
df_trna = df_trna.explode("treatment_rna_token").dropna(subset=["treatment_rna_token"])

df_trna["treatment_rna_norm"] = df_trna["treatment_rna_token"].apply(norm_name)

print("\nV4-04t — df_trna sample:")
display(df_trna.head(20))

df_trna_codes = df_trna.merge(
    rna_map[["injected_rna_norm", COL_RNA_PBASE]],
    left_on="treatment_rna_norm",
    right_on="injected_rna_norm",
    how="left",
)

print("\nV4-04t — df_trna_codes sample:")
display(df_trna_codes[["roi_dir", "treatment_rna_token", COL_RNA_PBASE]].head(20))

# ── 2) explode treatment plasmids → map to plasmid_base_code ────────────────

df_tpl = df_enrich[["roi_dir", "treatment_plasmid_names_sheet"]].dropna().copy()
df_tpl["treatment_pl_token"] = df_tpl["treatment_plasmid_names_sheet"].apply(split_pipe_or_single)
df_tpl = df_tpl.explode("treatment_pl_token").dropna(subset=["treatment_pl_token"])

df_tpl["treatment_pl_norm"] = df_tpl["treatment_pl_token"].apply(norm_name)

print("\nV4-04t — df_tpl sample:")
display(df_tpl.head(20))

df_tpl_codes = df_tpl.merge(
    plasmid_map[["injected_plasmid_norm", COL_PL_PBASE]],
    left_on="treatment_pl_norm",
    right_on="injected_plasmid_norm",
    how="left",
)

print("\nV4-04t — df_tpl_codes sample:")
display(df_tpl_codes[["roi_dir", "treatment_pl_token", COL_PL_PBASE]].head(20))

# ── 3) unify treatment plasmid codes (from RNA and plasmid injectors) ────────

treat_plasmids = []

if len(df_trna_codes):
    treat_plasmids.append(
        df_trna_codes.rename(columns={COL_RNA_PBASE: "plasmid_code"})[["roi_dir", "plasmid_code"]]
    )
if len(df_tpl_codes):
    treat_plasmids.append(
        df_tpl_codes.rename(columns={COL_PL_PBASE: "plasmid_code"})[["roi_dir", "plasmid_code"]]
    )

if treat_plasmids:
    df_treat_plasmids = pd.concat(treat_plasmids, ignore_index=True)
    df_treat_plasmids = df_treat_plasmids.dropna(subset=["plasmid_code"])
else:
    df_treat_plasmids = pd.DataFrame(columns=["roi_dir", "plasmid_code"])

print("\nV4-04t — df_treat_plasmids sample:")
display(df_treat_plasmids.head(20))

# ── 4) join treatment plasmid codes → constructs → fluor, tag, localization ─

# If constructs_ft already exists from V4-04, we can reuse it.
# Otherwise re-build it here (same logic as in V4-04).

try:
    _ = constructs_ft
except NameError:
    constructs_small = constructs[["plasmid_code", "fluor_code", "tag_code", "tag_pos"]].copy()
    fluors_small = fluors.rename(columns={"nickname": "fluor_code"})[
        ["fluor_code", "excitation_nm", "emission_nm", "note", "aliases"]
    ].copy()
    tags_small = tags.rename(columns={"nickname": "tag_code", "localization": "tag_localization"})[
        ["tag_code", "tag_localization", "note", "citation_link", "aliases"]
    ].copy()

    constructs_f = constructs_small.merge(fluors_small, on="fluor_code", how="left")
    constructs_ft = constructs_f.merge(tags_small, on="tag_code", how="left")

df_treat_markers = df_treat_plasmids.merge(
    constructs_ft[["plasmid_code", "fluor_code", "tag_code", "tag_localization"]],
    on="plasmid_code",
    how="left",
)

print("\nV4-04t — df_treat_markers sample:")
display(
    df_treat_markers[
        ["roi_dir", "plasmid_code", "fluor_code", "tag_code", "tag_localization"]
    ].head(20)
)

# ── 5) aggregate per ROI into treatment marker fields ────────────────────────

def join_unique(items):
    out = []
    seen = set()
    for x in items:
        if x is None or (isinstance(x, float) and pd.isna(x)):
            continue
        sx = str(x).strip()
        if not sx:
            continue
        if sx not in seen:
            seen.add(sx)
            out.append(sx)
    return "|".join(out) if out else None

def agg_treatment_markers(subdf):
    fluor_codes = join_unique(subdf["fluor_code"].tolist())
    tag_codes   = join_unique(subdf["tag_code"].tolist())
    locs        = join_unique(subdf["tag_localization"].tolist())

    fusion_labels = []
    for fc, tc in zip(subdf["fluor_code"], subdf["tag_code"]):
        if pd.isna(fc) or pd.isna(tc):
            continue
        fusion_labels.append(f"{fc}::{tc}")
    fusion_labels = join_unique(fusion_labels)

    fluor_org = []
    for fc, loc in zip(subdf["fluor_code"], subdf["tag_localization"]):
        if pd.isna(fc) or pd.isna(loc):
            continue
        fluor_org.append(f"{fc}({loc})")
    fluor_org = join_unique(fluor_org)

    return pd.Series({
        "treatment_marker_fluor_codes": fluor_codes,
        "treatment_marker_tag_codes": tag_codes,
        "treatment_marker_localizations": locs,
        "treatment_marker_fusion_labels": fusion_labels,
        "treatment_fluor_organelles": fluor_org,
    })

if len(df_treat_markers):
    t_agg = (
        df_treat_markers
        .groupby("roi_dir", dropna=False)
        .apply(agg_treatment_markers)
        .reset_index()
    )
else:
    t_agg = pd.DataFrame(columns=["roi_dir"])

print("\nV4-04t — t_agg (per-ROI treatment markers) sample:")
display(t_agg.head(20))

before_cols = set(df_enrich.columns)
df_enrich = df_enrich.merge(t_agg, on="roi_dir", how="left")
after_cols = set(df_enrich.columns)

print("\nV4-04t — df_enrich new columns:", sorted(after_cols - before_cols))

V4-04t — RNA map: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/raw/Unique_injected_rna__preview_dqm.xlsx
V4-04t — plasmid map: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/raw/Unique_injected_plasmid__preview_dqm.xlsx
V4-04t — rna_map columns: ['injected_rna', 'plasmid_base_code']
V4-04t — plasmid_map columns: ['injected_plasmid', 'plasmid_base_code']

V4-04t — df_trna sample:

,roi_dir,treatment_rna_names_sheet,treatment_rna_token,treatment_rna_norm
10,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
11,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
12,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
13,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
14,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
15,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
16,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
17,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
18,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
19,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
20,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
21,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
22,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
23,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
24,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
25,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
26,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
27,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
28,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS
29,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,phiC-NLS,phiC-NLS

V4-04t — df_trna_codes sample:

,roi_dir,treatment_rna_token,plasmid_base_code
0,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
1,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
2,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
3,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
4,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
5,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
6,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
7,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
8,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
9,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
10,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
11,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
12,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
13,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
14,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
15,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
16,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
17,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
18,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN
19,/clusterfs/vast/abcabc/Korra_Foundation/202505...,phiC-NLS,NaN

V4-04t — df_tpl sample:

Empty DataFrame
Columns: [roi_dir, treatment_plasmid_names_sheet, treatment_pl_token, treatment_pl_norm]
Index: []

V4-04t — df_tpl_codes sample:

Empty DataFrame
Columns: [roi_dir, treatment_pl_token, plasmid_base_code]
Index: []

V4-04t — df_treat_plasmids sample:

Empty DataFrame
Columns: [roi_dir, plasmid_code]
Index: []

V4-04t — df_treat_markers sample:

Empty DataFrame
Columns: [roi_dir, plasmid_code, fluor_code, tag_code, tag_localization]
Index: []

V4-04t — t_agg (per-ROI treatment markers) sample:

Empty DataFrame
Columns: [roi_dir]
Index: []

V4-04t — df_enrich new columns: []

In [126]:
# V4-04u — build all_unique_organelles / all_fluor_organelles 
#          from genotype + treatment markers (if present)

import pandas as pd

cols = set(df_enrich.columns)

has_geno_loc   = "genotype_marker_localizations"    in cols
has_treat_loc  = "treatment_marker_localizations"   in cols
has_geno_floc  = "genotype_marker_fluor_loc_labels" in cols
has_treat_floc = "treatment_marker_fluor_loc_labels" in cols

print("V4-04u — marker columns present:")
print("  genotype_marker_localizations:    ", has_geno_loc)
print("  treatment_marker_localizations:   ", has_treat_loc)
print("  genotype_marker_fluor_loc_labels: ", has_geno_floc)
print("  treatment_marker_fluor_loc_labels:", has_treat_floc)

def split_pipe(val):
    if pd.isna(val) or not isinstance(val, str) or not val.strip():
        return []
    return [x.strip() for x in val.split("|") if x.strip()]

def join_unique(items):
    out = []
    seen = set()
    for x in items:
        if not x:
            continue
        sx = str(x).strip()
        if not sx or sx in seen:
            continue
        seen.add(sx)
        out.append(sx)
    return "|".join(out) if out else None

# ─────────────────────────────────────────
# 1) all_unique_organelles
# ─────────────────────────────────────────

def row_all_orgs(row):
    parts = []
    if has_geno_loc:
        parts.extend(split_pipe(row.get("genotype_marker_localizations")))
    if has_treat_loc:
        parts.extend(split_pipe(row.get("treatment_marker_localizations")))
    return join_unique(parts)

df_enrich["all_unique_organelles"] = df_enrich.apply(row_all_orgs, axis=1)

# ─────────────────────────────────────────
# 2) all_fluor_organelles
#    (fluor(localization) labels)
# ─────────────────────────────────────────

def row_all_fluor_orgs(row):
    parts = []
    if has_geno_floc:
        parts.extend(split_pipe(row.get("genotype_marker_fluor_loc_labels")))
    if has_treat_floc:
        parts.extend(split_pipe(row.get("treatment_marker_fluor_loc_labels")))
    return join_unique(parts)

df_enrich["all_fluor_organelles"] = df_enrich.apply(row_all_fluor_orgs, axis=1)

# ─────────────────────────────────────────
# 3) QC
# ─────────────────────────────────────────

print("\nV4-04u — all_unique_organelles coverage:")
print(df_enrich["all_unique_organelles"].notna().value_counts())

print("\nV4-04u — sample rows with non-empty all_unique_organelles:")
display(
    df_enrich.loc[
        df_enrich["all_unique_organelles"].notna(),
        [
            "roi_dir",
            "genotype_marker_localizations" if has_geno_loc else None,
            "treatment_marker_localizations" if has_treat_loc else None,
            "all_unique_organelles",
            "all_fluor_organelles",
        ],
    ].dropna(axis=1, how="all").head(20)
)

# optional QC on treatment markers — only if treatment columns exist
if has_treat_loc:
    print("\nV4-04u — sample rows with treatment markers:")
    display(
        df_enrich.loc[
            df_enrich["treatment_marker_localizations"].notna(),
            [
                "roi_dir",
                "treatment_rna_names_sheet" if "treatment_rna_names_sheet" in cols else None,
                "treatment_plasmid_names_sheet" if "treatment_plasmid_names_sheet" in cols else None,
                "treatment_marker_fluor_codes" if "treatment_marker_fluor_codes" in cols else None,
                "treatment_marker_tag_codes" if "treatment_marker_tag_codes" in cols else None,
                "treatment_marker_localizations",
                "all_unique_organelles",
                "all_fluor_organelles",
            ],
        ].dropna(axis=1, how="all").head(20)
    )
else:
    print("\nV4-04u — no treatment_marker_* columns present; all_unique_organelles is genotype-only.")

V4-04u — marker columns present:
  genotype_marker_localizations:     True
  treatment_marker_localizations:    False
  genotype_marker_fluor_loc_labels:  False
  treatment_marker_fluor_loc_labels: False

V4-04u — all_unique_organelles coverage:
all_unique_organelles
False    853
True      16
Name: count, dtype: int64

V4-04u — sample rows with non-empty all_unique_organelles:

KeyError: '[None] not in index'

In [105]:
# V4-05 — build final v4 outputs and write CSVs (with treatment-name columns)

import pandas as pd

print("V4-05 — starting from df_enrich shape:", df_enrich.shape)

# ---------------------------------------------------------------------
# 1) Basic QC: row counts and duplicates by roi_dir
# ---------------------------------------------------------------------

n_rows = len(df_enrich)
n_roi_unique = df_enrich["roi_dir"].nunique()
print("V4-05 — df_enrich rows:", n_rows)
print("V4-05 — unique roi_dir:", n_roi_unique)

dups = df_enrich[df_enrich["roi_dir"].duplicated(keep=False)]
print("V4-05 — duplicate roi_dir rows:", len(dups))
if len(dups):
    print("V4-05 — sample duplicates:")
    display(dups[["roi_dir", "bruker_roi_id"]].head(20))

# ---------------------------------------------------------------------
# 2) Define final column sets
# ---------------------------------------------------------------------

base_for_db_cols = [
    # IDs / structural
    "roi_dir",
    "bruker_roi_id",
    "plate_date",
    "plate_id_filled",
    "slot_id_filled",
    "roi_index_within_slot",
    "dataset_slug",
    "experiment_folder",
    "fish_id",
    "fish_number",
    "fish_age_hpf",
    "roi_anatomy",
    "roi_tiffs",

    # imaging timing
    "date_experiment",
    "Date imaged",
    "date_mount",

    # ZF genotypes (raw from sheet)
    "ZF female genotype",
    "ZF male genotype",

    # parent-map-derived genotype
    "genotype_base_codes",
    "genotype_allele_codes",

    # treatment codes (from parent_map)
    "treatment_plasmid_base_codes",
    "treatment_rna_base_codes",

    # genotype markers and organelles
    "genotype_marker_fluor_codes",
    "genotype_marker_tag_codes",
    "genotype_marker_localizations",
    "genotype_marker_fusion_labels",
    "all_unique_organelles",
    "all_fluor_organelles",

    # provenance
    "link_source",
]

# imaging-sheet treatment names (if present)
sheet_treatment_cols = [
    "treatment_plasmid_names_sheet",
    "treatment_rna_names_sheet",
    "treatment_protein_names_sheet",
    "treatment_dye_names_sheet",
]

for_db_cols = base_for_db_cols + sheet_treatment_cols

missing_for_db = [c for c in for_db_cols if c not in df_enrich.columns]
if missing_for_db:
    print("V4-05 — WARNING: these requested for_db_cols are missing and will be dropped:", missing_for_db)
    for_db_cols = [c for c in for_db_cols if c in df_enrich.columns]

df_for_db = df_enrich[for_db_cols].copy()

print("\nV4-05 — df_for_db shape:", df_for_db.shape)
print("V4-05 — df_for_db columns:")
print(for_db_cols)

# ---------------------------------------------------------------------
# 3) Write outputs
# ---------------------------------------------------------------------

OUT_DIR = ROOT / "seed_kits" / "legacy_wrangling_v2" / "working"

FULL_OUT = OUT_DIR / "legacy_imaging_annotations_v4.csv"
DB_OUT   = OUT_DIR / "legacy_imaging_annotations_for_db_v4.csv"

df_enrich.to_csv(FULL_OUT, index=False)
df_for_db.to_csv(DB_OUT, index=False)

print("\nV4-05 — wrote full annotations to:", FULL_OUT)
print("V4-05 — wrote DB subset to:", DB_OUT)

# ---------------------------------------------------------------------
# 4) Quick summary of DB subset for sanity
# ---------------------------------------------------------------------

print("\nV4-05 — DB subset sample:")
display(df_for_db.head(20))

print("\nV4-05 — DB subset organelle coverage:")
print(
    df_for_db["all_unique_organelles"].notna().value_counts()
)

V4-05 — starting from df_enrich shape: (1118, 77)
V4-05 — df_enrich rows: 1118
V4-05 — unique roi_dir: 975
V4-05 — duplicate roi_dir rows: 282
V4-05 — sample duplicates:

,roi_dir,bruker_roi_id
54,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot1-roi1
55,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot1-roi2
56,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot1-roi3
57,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot2-roi1
58,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot2-roi2
59,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot2-roi3
60,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot2-roi4
61,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot2-roi5
62,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot2-roi6
63,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot3-roi1
64,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot3-roi2
65,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250520-plate6-slot3-roi3
90,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot1-roi1
91,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot1-roi2
92,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot2-roi1
93,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot2-roi2
94,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot3-roi1
95,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot3-roi2
96,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot4-roi1
97,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250523-plate10-slot4-roi2

V4-05 — df_for_db shape: (1118, 33)
V4-05 — df_for_db columns:
['roi_dir', 'bruker_roi_id', 'plate_date', 'plate_id_filled', 'slot_id_filled', 'roi_index_within_slot', 'dataset_slug', 'experiment_folder', 'fish_id', 'fish_number', 'fish_age_hpf', 'roi_anatomy', 'roi_tiffs', 'date_experiment', 'Date imaged', 'date_mount', 'ZF female genotype', 'ZF male genotype', 'genotype_base_codes', 'genotype_allele_codes', 'treatment_plasmid_base_codes', 'treatment_rna_base_codes', 'genotype_marker_fluor_codes', 'genotype_marker_tag_codes', 'genotype_marker_localizations', 'genotype_marker_fusion_labels', 'all_unique_organelles', 'all_fluor_organelles', 'link_source', 'treatment_plasmid_names_sheet', 'treatment_rna_names_sheet', 'treatment_protein_names_sheet', 'treatment_dye_names_sheet']

V4-05 — wrote full annotations to: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/working/legacy_imaging_annotations_v4.csv
V4-05 — wrote DB subset to: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/working/legacy_imaging_annotations_for_db_v4.csv

V4-05 — DB subset sample:

,roi_dir,bruker_roi_id,plate_date,plate_id_filled,slot_id_filled,roi_index_within_slot,dataset_slug,experiment_folder,fish_id,fish_number,...,genotype_marker_tag_codes,genotype_marker_localizations,genotype_marker_fusion_labels,all_unique_organelles,all_fluor_organelles,link_source,treatment_plasmid_names_sheet,treatment_rna_names_sheet,treatment_protein_names_sheet,treatment_dye_names_sheet
0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250428-plate1-slot1-roi1,20250428,1,1,1,20250428_mem_histone,20250428_mem_histone,fish1,1.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane)|mScarlet3S2(histone),sheet,None,mScarlet3-S2:H2B,None,None
1,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250428-plate1-slot1-roi2,20250428,1,1,2,20250428_mem_histone,20250428_mem_histone,fish1,1.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane)|mScarlet3S2(histone),sheet,None,mScarlet3-S2:H2B,None,None
2,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot1-roi1,20250429,2,1,1,20250429_mem_cytosol,20250429_mem_cytosol,fish1,1.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
3,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot1-roi2,20250429,2,1,2,20250429_mem_cytosol,20250429_mem_cytosol,fish1,1.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
4,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot2-roi1,20250429,2,2,1,20250429_mem_cytosol,20250429_mem_cytosol,fish2,2.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
5,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot3-roi1,20250429,2,3,1,20250429_mem_cytosol,20250429_mem_cytosol,fish3,3.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
6,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot3-roi2,20250429,2,3,2,20250429_mem_cytosol,20250429_mem_cytosol,fish3,3.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
7,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot4-roi1,20250429,2,4,1,20250429_mem_cytosol,20250429_mem_cytosol,fish4,4.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
8,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot4-roi2,20250429,2,4,2,20250429_mem_cytosol,20250429_mem_cytosol,fish4,4.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
9,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429-plate2-slot4-roi3,20250429,2,4,3,20250429_mem_cytosol,20250429_mem_cytosol,fish4,4.0,...,2xLynk,membrane,tdmSG::2xLynk,membrane,tdmSG(membrane),sheet,ef1a:mGold2s,None,None,None
10,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot1-roi1,20250513,3,1,1,20250513_skittles,20250513_skittles,fish1,1.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
11,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot1-roi2,20250513,3,1,2,20250513_skittles,20250513_skittles,fish1,1.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
12,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot1-roi3,20250513,3,1,3,20250513_skittles,20250513_skittles,fish1,1.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
13,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot2-roi1,20250513,3,2,1,20250513_skittles,20250513_skittles,fish10,10.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
14,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot3-roi1,20250513,3,3,1,20250513_skittles,20250513_skittles,fish11,11.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
15,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot3-roi2,20250513,3,3,2,20250513_skittles,20250513_skittles,fish11,11.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
16,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot4-roi1,20250513,3,4,1,20250513_skittles,20250513_skittles,fish12,12.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
17,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot4-roi2,20250513,3,4,2,20250513_skittles,20250513_skittles,fish12,12.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
18,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot4-roi3,20250513,3,4,3,20250513_skittles,20250513_skittles,fish12,12.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None
19,/clusterfs/vast/abcabc/Korra_Foundation/202505...,20250513-plate3-slot5-roi1,20250513,3,5,1,20250513_skittles,20250513_skittles,fish13,13.0,...,NaN,NaN,NaN,None,None,sheet,None,phiC-NLS,None,None

V4-05 — DB subset organelle coverage:
all_unique_organelles
True     922
False    196
Name: count, dtype: int64

In [106]:
# V4-06 — copy enriched outputs from working/ to final/

from pathlib import Path
import shutil

ROOT = Path("/Users/davekokel/Projects/carp_v2").resolve()
WORKING = ROOT / "seed_kits" / "legacy_wrangling_v2" / "working"
FINAL   = ROOT / "seed_kits" / "legacy_wrangling_v2" / "final"

FINAL.mkdir(parents=True, exist_ok=True)

src_full = WORKING / "legacy_imaging_annotations_v4.csv"
src_db   = WORKING / "legacy_imaging_annotations_for_db_v4.csv"

dest_full = FINAL / src_full.name
dest_db   = FINAL / src_db.name

print("Copying:")
print("  ", src_full, "->", dest_full)
print("  ", src_db,   "->", dest_db)

shutil.copy2(src_full, dest_full)
shutil.copy2(src_db, dest_db)

print("\nV4-06 — done. Final files:")
print("  ", dest_full)
print("  ", dest_db)

Copying:
   /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/working/legacy_imaging_annotations_v4.csv -> /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/final/legacy_imaging_annotations_v4.csv
   /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/working/legacy_imaging_annotations_for_db_v4.csv -> /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/final/legacy_imaging_annotations_for_db_v4.csv

V4-06 — done. Final files:
   /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/final/legacy_imaging_annotations_v4.csv
   /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling_v2/final/legacy_imaging_annotations_for_db_v4.csv

In [100]:
row = df_enrich[df_enrich["roi_dir"].str.contains("20250428_mem_histone/fish1_72hpf/roi1_tail")]
cols_show = [
    "roi_dir",
    "Data location",
    "ZF female genotype",
    "ZF male genotype",
    "treatment_plasmid_names_sheet",
    "treatment_rna_names_sheet",
    "treatment_protein_names_sheet",
    "treatment_dye_names_sheet",
]
display(row[cols_show])

,roi_dir,Data location,ZF female genotype,ZF male genotype,treatment_plasmid_names_sheet,treatment_rna_names_sheet,treatment_protein_names_sheet,treatment_dye_names_sheet
0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,X:\abcabc\Korra_Foundation\20250428_mem_histon...,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),ef1a:2xLynk:tdmSG(J) (F2 of allele 301),None,mScarlet3-S2:H2B,None,None