In [1]:
# CELL 1: Setup paths and load raw inputs

import pandas as pd
from pathlib import Path

# Base directories
BASE    = Path("/Users/davekokel/Projects/carp_v2")
RAW     = BASE / "seed_kits" / "legacy_wrangling" / "raw"
WORKING = BASE / "seed_kits" / "legacy_wrangling" / "working"

# Raw input files
roi_paths_path     = RAW / "2025-11-13-092338-korra_aang_roi_root_tiffs_good-3.xlsx"
imaging_sheet_path = RAW / "2025-11-13-124226-imaging_sheet.xlsx"
inj_plasmid_path   = RAW / "Unique_injected_plasmid__preview_dqm.xlsx"
inj_rna_path       = RAW / "Unique_injected_rna__preview_dqm.xlsx"
parent_map_path    = RAW / "Unique_parent_names__mom_dad_combined__preview_dqm.xlsx"
constructs_path    = RAW / "constructs_plasmid.csv"

# Where we'll write the new annotations CSV
annot_path = WORKING / "imaging_roi_annotations_AUTO_v2.csv"

df_roi        = pd.read_excel(roi_paths_path)
df_sheet      = pd.read_excel(imaging_sheet_path)
df_inj_plasm  = pd.read_excel(inj_plasmid_path)
df_inj_rna    = pd.read_excel(inj_rna_path)
df_parent_map = pd.read_excel(parent_map_path)
df_constructs = pd.read_csv(constructs_path)

print("df_roi:", df_roi.shape)
print("df_sheet:", df_sheet.shape)
print("df_inj_plasm:", df_inj_plasm.shape)
print("df_inj_rna:", df_inj_rna.shape)
print("df_parent_map:", df_parent_map.shape)
print("df_constructs:", df_constructs.shape)

df_roi.head(), df_sheet.head()

df_roi: (976, 7)
df_sheet: (306, 20)
df_inj_plasm: (25, 2)
df_inj_rna: (44, 2)
df_parent_map: (41, 3)
df_constructs: (287, 12)

(        date_experiment         fish               roi_rel  \
 0  20250428_mem_histone  fish1_72hpf             roi1_tail
 1  20250428_mem_histone  fish1_72hpf  roi2_hindbrain_spine
 2  20250429_mem_cytosol  fish1_24hpf                  roi1
 3  20250429_mem_cytosol  fish1_24hpf             roi1_test
 4  20250429_mem_cytosol  fish2_48hpf                  roi1

                roi_name  roi_tiffs  \
 0             roi1_tail       3206
 1  roi2_hindbrain_spine       9760
 2                  roi1       6873
 3             roi1_test         46
 4                  roi1       3180

                                              roi_dir dataset
 0  /clusterfs/vast/abcabc/Korra_Foundation/202504...   korra
 1  /clusterfs/vast/abcabc/Korra_Foundation/202504...   korra
 2  /clusterfs/vast/abcabc/Korra_Foundation/202504...   korra
 3  /clusterfs/vast/abcabc/Korra_Foundation/202504...   korra
 4  /clusterfs/vast/abcabc/Korra_Foundation/202504...   korra  ,
   date_mount mount_id                       ZF female genotype  \
 0 2025-11-12        1                                   casper
 1 2025-11-12        2                                   casper
 2 2025-11-11        1                                   casper
 3 2025-11-10        1  ef1a:2xLynk:tdmSG(J) (F1 of allele 301)
 4 2025-11-06      1.1                                   casper

                             ZF male genotype  \
 0   memrane tdmScarlet3S2 (F1 of allele 325)
 1   memrane tdmScarlet3S2 (F1 of allele 325)
 2   memrane tdmScarlet3S2 (F1 of allele 325)
 3  tdmScarlet3S2:H2B-tol2 (F1 of allele 324)
 4  ef1a:2xLynk:tdmChilada (F1 of allele 315)

                         additional plasmids injected  \
 0  MGCO-01(ef1a-2Xcox8A-linker-mStayGold-SV40-att...
 1  MGCO-60-Factin-A2UCOE-attb_entire+PDQM148-mSta...
 2  MGCO-01(ef1a-2Xcox8A-linker-mStayGold-SV40-att...
 3                                                NaN
 4                                                NaN

   additional mRNAs injected additonal proteins injected  \
 0                       NaN                         NaN
 1                       NaN                         NaN
 2                       NaN                         NaN
 3                       NaN                         NaN
 4               2xCox8A:mSG                         NaN

   additonal dye and chemicals  Date born Time mounted Mounting Orientation  \
 0                         NaN 2025-11-10     10:00:00                   DH
 1                         NaN 2025-11-10     10:00:00                   DH
 2                         NaN 2025-11-08     13:00:00                   DH
 3                         NaN 2025-11-08     11:00:00                   DH
 4                         NaN 2025-11-04     11:00:00                   DH

   Date screened/Initial feedback Date imaged Time placed in scope  \
 0                            NaN  2025-11-12                  NaN
 1                            NaN  2025-11-12                  NaN
 2                            NaN  2025-11-11                  NaN
 3                            NaN  2025-11-10                  NaN
 4                            NaN  2025-11-06                  NaN

   Start of imaging time End of imaging time  \
 0                   NaN                 NaN
 1                   NaN                 NaN
 2                   NaN                 NaN
 3                   NaN                 NaN
 4                   NaN                 NaN

                                     Imaged Locations  \
 0  skin, spinal_cord, hindbrain, brain, muscle, b...
 1                                                NaN
 2        skin, spinal_cord, hindbrain, brain, muscle
 3  skin, spinal_cord, hindbrain, brain, muscle, b...
 4        skin, spinal_cord, hindbrain, brain, muscle

   Unique Targets with blanks Unique Targets  \
 0                        NaN            NaN
 1                        NaN            NaN
 2                        NaN            NaN
 3                        NaN            NaN
 4                        NaN            NaN

                                      Data location
 0     X:\abcabc\Korra_Foundation\20251112_mem-mito
 1   X:\abcabc\Exploratory_fish\20251112_mem-moesin
 2      X:\abcabc\Aang_Foundation\20251107_mem-mito
 3  X:\abcabc\Korra_Foundation\20251110_mem-histone
 4      X:\abcabc\Aang_Foundation\20251106_mem-mito  )

In [2]:
# CELL 2: Load flat ROI markers (one row per ROI/marker)

flat_path = WORKING / "roi_all_markers_flat_COMPLETE.csv"  # adjust if your final flat file has a different name
df_flat = pd.read_csv(flat_path)

print("df_flat:", df_flat.shape)
df_flat.head()

df_flat: (976, 24)

,roi_dir,date_experiment,fish,roi_name,date_born,parent_female_final,parent_male_final,genotype_base_codes,genotype_allele_codes,genotype_marker_fluor_codes,...,treatment_marker_tag_codes,all_marker_fluor_codes,additional plasmids injected,additional mRNAs injected,additonal proteins injected,additonal dye and chemicals,Date born,ZF female genotype,ZF male genotype,Data location
0,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250428_mem_histone,fish1_72hpf,roi1_tail,2025-04-26,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),ef1a:2xLynk:tdmSG(J) (F2 of allele 301),pDQM005,"pDQM005:301,pDQM005:301",tdmSG,...,NaN,tdmSG,NaN,mScarlet3-S2:H2B,NaN,NaN,2025-04-26,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),ef1a:2xLynk:tdmSG(J) (F2 of allele 301),X:\abcabc\Korra_Foundation\20250428_mem_histon...
1,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250428_mem_histone,fish1_72hpf,roi2_hindbrain_spine,2025-04-26,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),ef1a:2xLynk:tdmSG(J) (F2 of allele 301),pDQM005,"pDQM005:301,pDQM005:301",tdmSG,...,NaN,tdmSG,NaN,mScarlet3-S2:H2B,NaN,NaN,2025-04-26,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),ef1a:2xLynk:tdmSG(J) (F2 of allele 301),X:\abcabc\Korra_Foundation\20250428_mem_histon...
2,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429_mem_cytosol,fish1_24hpf,roi1,2025-04-29,membrane Halo,membrane Halo,Swinburne,"Swinburne:Swinburne,Swinburne:Swinburne",Halo,...,NaN,"Halo,mGold2s",ef1a:mGold2s,NaN,NaN,NaN,2025-04-29,membrane Halo,membrane Halo,X:\abcabc\Korra_Foundation\20250429_mem_cytoso...
3,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429_mem_cytosol,fish1_24hpf,roi1_test,2025-04-29,membrane Halo,membrane Halo,Swinburne,"Swinburne:Swinburne,Swinburne:Swinburne",Halo,...,NaN,"Halo,mGold2s",ef1a:mGold2s,NaN,NaN,NaN,2025-04-29,membrane Halo,membrane Halo,X:\abcabc\Korra_Foundation\20250429_mem_cytoso...
4,/clusterfs/vast/abcabc/Korra_Foundation/202504...,20250429_mem_cytosol,fish2_48hpf,roi1,2025-04-29,membrane Halo,membrane Halo,Swinburne,"Swinburne:Swinburne,Swinburne:Swinburne",Halo,...,NaN,"Halo,mGold2s",ef1a:mGold2s,NaN,NaN,NaN,2025-04-29,membrane Halo,membrane Halo,X:\abcabc\Korra_Foundation\20250429_mem_cytoso...

In [5]:
# CELL 3: Define aggregators that keep ALL marker codes

def agg_uniq(series: pd.Series) -> str | None:
    """
    Aggregate all non-empty, non-NaN values into a sorted, comma-separated list.
    Returns None if there are no real values.
    """
    vals = []
    for x in series:
        if pd.isna(x):
            continue
        s = str(x).strip()
        if not s:
            continue
        vals.append(s)
    if not vals:
        return None
    uniq = sorted(set(vals))
    return ",".join(uniq)

In [7]:
# CELL 4: Aggregate flat markers into per-ROI annotations (v2)

# Columns we want to aggregate as "sets" of codes
marker_cols = [
    "genotype_marker_fluor_codes",
    "genotype_marker_tag_codes",
    "treatment_plasmid_base_codes",
    "treatment_rna_base_codes",
    "treatment_marker_fluor_codes",
    "treatment_marker_tag_codes",
    "all_marker_fluor_codes",
]

# Determine ROI key and meta columns
key_col = "roi_dir"  # flat CSVs use roi_dir as the ROI key

# meta_cols should NOT include the key_col itself
meta_cols = [c for c in df_flat.columns if c not in marker_cols + [key_col]]

grouped = df_flat.groupby(key_col)

# Meta: take first row per ROI for these columns
df_meta = grouped[meta_cols].first().reset_index()  # roi_dir comes from the index

# Markers: aggregate all codes per ROI using agg_uniq
df_markers = grouped[marker_cols].agg(agg_uniq).reset_index()

# Merge back into a single per-ROI annotation dataframe
df_annot_v2 = pd.merge(df_meta, df_markers, on=key_col, how="inner")

print("df_annot_v2:", df_annot_v2.shape)
df_annot_v2.head()

df_annot_v2: (976, 24)

,roi_dir,date_experiment,fish,roi_name,date_born,parent_female_final,parent_male_final,genotype_base_codes,genotype_allele_codes,additional plasmids injected,...,ZF female genotype,ZF male genotype,Data location,genotype_marker_fluor_codes,genotype_marker_tag_codes,treatment_plasmid_base_codes,treatment_rna_base_codes,treatment_marker_fluor_codes,treatment_marker_tag_codes,all_marker_fluor_codes
0,/clusterfs/vast/abcabc/Aang_Foundation/2025072...,20250721_72hpf_mrna_mSG_organelle_LLS-SIM,er_roi1,er_roi1,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,/clusterfs/vast/abcabc/Aang_Foundation/2025072...,20250721_72hpf_mrna_mSG_organelle_LLS-SIM,er_roi2,er_roi2,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,/clusterfs/vast/abcabc/Aang_Foundation/2025072...,20250721_72hpf_mrna_mSG_organelle_LLS-SIM,er_roi3,er_roi3,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,/clusterfs/vast/abcabc/Aang_Foundation/2025072...,20250721_72hpf_mrna_mSG_organelle_LLS-SIM,mito_roi1,mito_roi1,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,/clusterfs/vast/abcabc/Aang_Foundation/2025072...,20250721_72hpf_mrna_mSG_organelle_LLS-SIM,mito_roi2,mito_roi2,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [8]:
# CELL 5: Write per-ROI annotations to imaging_roi_annotations_AUTO_v2.csv

df_annot_v2.to_csv(annot_path, index=False)
print("Wrote:", annot_path, "with", len(df_annot_v2), "rows")

Wrote: /Users/davekokel/Projects/carp_v2/seed_kits/legacy_wrangling/working/imaging_roi_annotations_AUTO_v2.csv with 976 rows

In [9]:
# CELL X: Inspect tags in the import flat file

from pathlib import Path

flat_import_path = BASE / "seed_kits" / "legacy_import" / "working" / "roi_all_markers_flat_complete.csv"
df_flat_import = pd.read_csv(flat_import_path)

print("df_flat_import:", df_flat_import.shape)
df_flat_import.head()

df_flat_import: (217, 29)

,dataset_source,clutch_code,clutch_date,genotype_cross_label,genotype_base_codes,genotype_allele_codes,genotype_pretty,genotype_marker_fluor_codes,genotype_marker_tag_codes,treat_code,...,parent_female_filled,parent_male_filled,date_mount,mount_id,plate_id_filled,slot_id_filled,data_location_filled,roi_index,roi_name,data_path
0,mem_histone,IMG_CLT_20250130_01,2025-01-30,NaN,NaN,NaN,NaN,NaN,NaN,IMG_TRT_001,...,casper/rnf,casper/rnf,2025-01-31,NaN,SYN_20250131_plate1,SYN_20250131_plate1-slot1,U:\Data\20240911_Korra_Foundation\20250131_mem...,1,U:\Data\20240911_Korra_Foundation\20250131_mem...,U:\Data\20240911_Korra_Foundation\20250131_mem...
1,mem_histone,IMG_CLT_20250130_01,2025-01-30,NaN,NaN,NaN,NaN,NaN,NaN,IMG_TRT_001,...,casper/rnf,casper/rnf,2025-01-31,NaN,SYN_20250131_plate1,SYN_20250131_plate1-slot1,U:\Data\20240911_Korra_Foundation\20250131_mem...,1,U:\Data\20240911_Korra_Foundation\20250131_mem...,U:\Data\20240911_Korra_Foundation\20250131_mem...
2,mem_histone,IMG_CLT_20250203_02,2025-02-03,pDQM005_301,pDQM005,pDQM005:301,pDQM005(301),"tdmSG,tdmStayGold",NaN,IMG_TRT_004,...,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),casper/rnf,2025-02-06,NaN,SYN_20250206_plate1,SYN_20250206_plate1-slot1,U:\Data\20240911_Korra_Foundation\20250204_mem...,1,U:\Data\20240911_Korra_Foundation\20250204_mem...,U:\Data\20240911_Korra_Foundation\20250204_mem...
3,mem_histone,IMG_CLT_20250203_02,2025-02-03,pDQM005_301,pDQM005,pDQM005:301,pDQM005(301),"tdmSG,tdmStayGold",NaN,IMG_TRT_004,...,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),casper/rnf,2025-02-05,NaN,SYN_20250205_plate1,SYN_20250205_plate1-slot1,U:\Data\20240911_Korra_Foundation\20250204_mem...,1,U:\Data\20240911_Korra_Foundation\20250204_mem...,U:\Data\20240911_Korra_Foundation\20250204_mem...
4,mem_histone,IMG_CLT_20250203_02,2025-02-03,pDQM005_301,pDQM005,pDQM005:301,pDQM005(301),"tdmSG,tdmStayGold",NaN,IMG_TRT_004,...,ef1a:2xLynk:tdmSG(J) (F2 of allele 301),casper/rnf,2025-02-05,NaN,SYN_20250205_plate1,SYN_20250205_plate1-slot1,U:\Data\20240911_Korra_Foundation\20250204_mem...,1,U:\Data\20240911_Korra_Foundation\20250204_mem...,U:\Data\20240911_Korra_Foundation\20250204_mem...

In [10]:
# CELL: Compare import vs working flat markers for a specific ROI

roi_example = "U:\\Data\\20240911_Korra_Foundation\\20250204_mem..."  # use the full path you saw in df_flat_import

print("=== IMPORT FLAT (legacy_import/working) ===")
display(
    df_flat_import.loc[
        df_flat_import["data_path"].astype(str).str.startswith(roi_example),
        [
            "clutch_code",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
        ],
    ]
)

print("=== WORKING FLAT (legacy_wrangling/working) ===")
display(
    df_flat.loc[
        df_flat["roi_dir"].astype(str).str.startswith(roi_example),
        [
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
            "all_marker_fluor_codes",
        ],
    ]
)

=== IMPORT FLAT (legacy_import/working) ===

Empty DataFrame
Columns: [clutch_code, genotype_marker_fluor_codes, genotype_marker_tag_codes, treatment_plasmid_base_codes, treatment_rna_base_codes, treatment_marker_fluor_codes, treatment_marker_tag_codes]
Index: []

=== WORKING FLAT (legacy_wrangling/working) ===

Empty DataFrame
Columns: [genotype_marker_fluor_codes, genotype_marker_tag_codes, treatment_plasmid_base_codes, treatment_rna_base_codes, treatment_marker_fluor_codes, treatment_marker_tag_codes, all_marker_fluor_codes]
Index: []

In [11]:
# CELL A: show first few import rows that have genotype_marker_tag_codes

rows_with_tags_import = df_flat_import[
    df_flat_import["genotype_marker_tag_codes"].notna()
    & (df_flat_import["genotype_marker_tag_codes"].astype(str).str.strip() != "")
]

print("rows_with_tags_import:", rows_with_tags_import.shape)
rows_with_tags_import.head(10)[[
    "clutch_code",
    "genotype_marker_fluor_codes",
    "genotype_marker_tag_codes",
    "data_path",
]]

rows_with_tags_import: (44, 29)

,clutch_code,genotype_marker_fluor_codes,genotype_marker_tag_codes,data_path
140,IMG_CLT_20250721_02,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250722_mrna_mito-m...
141,IMG_CLT_20250723_01,tdmChilada,2xLynk,X:\abcabc\Korra_Foundation\20250724_mem-mchila...
148,IMG_CLT_20250807_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250808_mem_organelle
149,IMG_CLT_20250807_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250808_mem_organelle
150,IMG_CLT_20250818_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250819_mem_mito
151,IMG_CLT_20250818_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250819_mem_mito
152,IMG_CLT_20250818_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250819_mem_ER
154,IMG_CLT_20250820_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250821_mem_mito
155,IMG_CLT_20250820_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250821_mem_mito
160,IMG_CLT_20250825_01,tdmChilada,2xLynk,X:\abcabc\Aang_Foundation\20250827_mem_actin

In [12]:
# CELL B: compare that ROI between import and working

example_path = rows_with_tags_import.iloc[2]["data_path"]
print("Example data_path:", example_path)

print("\n=== IMPORT FLAT (legacy_import/working) ===")
display(
    df_flat_import.loc[
        df_flat_import["data_path"] == example_path,
        [
            "clutch_code",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
        ],
    ]
)

print("\n=== WORKING FLAT (legacy_wrangling/working) ===")
display(
    df_flat.loc[
        df_flat["roi_dir"] == example_path,
        [
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
            "all_marker_fluor_codes",
        ],
    ]
)

Example data_path: X:\abcabc\Aang_Foundation\20250808_mem_organelle

=== IMPORT FLAT (legacy_import/working) ===

,clutch_code,genotype_marker_fluor_codes,genotype_marker_tag_codes,treatment_plasmid_base_codes,treatment_rna_base_codes,treatment_marker_fluor_codes,treatment_marker_tag_codes
148,IMG_CLT_20250807_01,tdmChilada,2xLynk,MGCO-15,NaN,mStayGold,LAMP1
149,IMG_CLT_20250807_01,tdmChilada,2xLynk,MGCO-15,NaN,mStayGold,LAMP1

=== WORKING FLAT (legacy_wrangling/working) ===

Empty DataFrame
Columns: [genotype_marker_fluor_codes, genotype_marker_tag_codes, treatment_plasmid_base_codes, treatment_rna_base_codes, treatment_marker_fluor_codes, treatment_marker_tag_codes, all_marker_fluor_codes]
Index: []

In [13]:
# CELL: Inspect this ROI in both import and working flat DataFrames

example_path = "X:\\abcabc\\Aang_Foundation\\20250808_mem_organelle"

print("=== IMPORT FLAT (legacy_import/working) ===")
display(
    df_flat_import.loc[
        df_flat_import["data_path"] == example_path,
        [
            "clutch_code",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
        ],
    ]
)

print("\n=== WORKING FLAT (legacy_wrangling/working) ===")
display(
    df_flat.loc[
        df_flat["roi_dir"] == example_path,
        [
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
            "all_marker_fluor_codes",
        ],
    ]
)

=== IMPORT FLAT (legacy_import/working) ===

,clutch_code,genotype_marker_fluor_codes,genotype_marker_tag_codes,treatment_plasmid_base_codes,treatment_rna_base_codes,treatment_marker_fluor_codes,treatment_marker_tag_codes
148,IMG_CLT_20250807_01,tdmChilada,2xLynk,MGCO-15,NaN,mStayGold,LAMP1
149,IMG_CLT_20250807_01,tdmChilada,2xLynk,MGCO-15,NaN,mStayGold,LAMP1

=== WORKING FLAT (legacy_wrangling/working) ===

Empty DataFrame
Columns: [genotype_marker_fluor_codes, genotype_marker_tag_codes, treatment_plasmid_base_codes, treatment_rna_base_codes, treatment_marker_fluor_codes, treatment_marker_tag_codes, all_marker_fluor_codes]
Index: []

In [14]:
# CELL: Find matching roi_dir(s) in WORKING flat for a known data_path tail

tail = "Aang_Foundation\\20250808_mem_organelle"

print("Looking for tail:", tail)

matches = df_flat[df_flat["roi_dir"].astype(str).str.contains(tail, case=False, na=False)]

print("df_flat matches:", matches.shape)
display(
    matches[
        [
            "roi_dir",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
            "all_marker_fluor_codes",
        ]
    ].head(10)
)

Looking for tail: Aang_Foundation\20250808_mem_organelle
df_flat matches: (0, 24)

Empty DataFrame
Columns: [roi_dir, genotype_marker_fluor_codes, genotype_marker_tag_codes, treatment_plasmid_base_codes, treatment_rna_base_codes, treatment_marker_fluor_codes, treatment_marker_tag_codes, all_marker_fluor_codes]
Index: []

In [15]:
# CELL C: Inspect working flat columns and some keys

print("df_flat:", df_flat.shape)
print("df_flat columns:")
print(df_flat.columns.tolist())

print("\nSample df_flat rows:")
display(
    df_flat.head(10)[
        [
            col
            for col in df_flat.columns
            if any(k in col for k in ["roi", "data", "clutch", "plate", "slot"])
        ]
    ]
)

df_flat: (976, 24)
df_flat columns:
['roi_dir', 'date_experiment', 'fish', 'roi_name', 'date_born', 'parent_female_final', 'parent_male_final', 'genotype_base_codes', 'genotype_allele_codes', 'genotype_marker_fluor_codes', 'genotype_marker_tag_codes', 'treatment_plasmid_base_codes', 'treatment_rna_base_codes', 'treatment_marker_fluor_codes', 'treatment_marker_tag_codes', 'all_marker_fluor_codes', 'additional plasmids injected', 'additional mRNAs injected', 'additonal proteins injected', 'additonal dye and chemicals', 'Date born', 'ZF female genotype', 'ZF male genotype', 'Data location']

Sample df_flat rows:

                                             roi_dir              roi_name
0  /clusterfs/vast/abcabc/Korra_Foundation/202504...             roi1_tail
1  /clusterfs/vast/abcabc/Korra_Foundation/202504...  roi2_hindbrain_spine
2  /clusterfs/vast/abcabc/Korra_Foundation/202504...                  roi1
3  /clusterfs/vast/abcabc/Korra_Foundation/202504...             roi1_test
4  /clusterfs/vast/abcabc/Korra_Foundation/202504...                  roi1
5  /clusterfs/vast/abcabc/Korra_Foundation/202504...                  roi1
6  /clusterfs/vast/abcabc/Korra_Foundation/202504...                  roi2
7  /clusterfs/vast/abcabc/Korra_Foundation/202504...                  roi1
8  /clusterfs/vast/abcabc/Korra_Foundation/202504...                  roi2
9  /clusterfs/vast/abcabc/Korra_Foundation/202504...                  roi3

In [16]:
# CELL D: Look for this clutch_code in both import and working flats

target_clutch = "IMG_CLT_20250807_01"

print("=== IMPORT FLAT rows with clutch_code =", target_clutch, "===")
display(
    df_flat_import.loc[
        df_flat_import["clutch_code"] == target_clutch,
        [
            "clutch_code",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
            "date_mount" if "date_mount" in df_flat_import.columns else "clutch_date",
            "plate_id_filled" if "plate_id_filled" in df_flat_import.columns else "experimental_plate_id",
            "slot_id_filled" if "slot_id_filled" in df_flat_import.columns else "experimental_slot_id",
        ],
    ].head(10)
)

print("\n=== WORKING FLAT rows that refer to the same clutch (if clutch_code exists) ===")
if "clutch_code" in df_flat.columns:
    display(
        df_flat.loc[
            df_flat["clutch_code"] == target_clutch,
            [
                "roi_dir",
                "genotype_marker_fluor_codes",
                "genotype_marker_tag_codes",
                "treatment_plasmid_base_codes",
                "treatment_rna_base_codes",
                "treatment_marker_fluor_codes",
                "treatment_marker_tag_codes",
                "all_marker_fluor_codes",
            ],
        ].head(10)
    )
else:
    print("Working flat has no 'clutch_code' column; we need a different join key.")

=== IMPORT FLAT rows with clutch_code = IMG_CLT_20250807_01 ===

,clutch_code,genotype_marker_fluor_codes,genotype_marker_tag_codes,treatment_plasmid_base_codes,treatment_rna_base_codes,treatment_marker_fluor_codes,treatment_marker_tag_codes,date_mount,plate_id_filled,slot_id_filled
148,IMG_CLT_20250807_01,tdmChilada,2xLynk,MGCO-15,NaN,mStayGold,LAMP1,2025-08-08,SYN_20250808_plate1,SYN_20250808_plate1-slot1
149,IMG_CLT_20250807_01,tdmChilada,2xLynk,MGCO-15,NaN,mStayGold,LAMP1,2025-08-08,SYN_20250808_plate1,SYN_20250808_plate1-slot1

=== WORKING FLAT rows that refer to the same clutch (if clutch_code exists) ===
Working flat has no 'clutch_code' column; we need a different join key.

In [17]:
# CELL: map Windows-style data_path to roi_dir-style path and match in df_flat

example_path_import = "X:\\abcabc\\Aang_Foundation\\20250808_mem_organelle"

# naïve mapping: X:\abcabc\ → /clusterfs/vast/abcabc/
example_roi_dir = example_path_import.replace("X:\\abcabc\\", "/clusterfs/vast/abcabc/")

print("example_path_import:", example_path_import)
print("mapped example_roi_dir:", example_roi_dir)

print("\n=== WORKING FLAT rows with roi_dir == mapped path ===")
matches = df_flat[df_flat["roi_dir"] == example_roi_dir]
print("matches shape:", matches.shape)
display(
    matches[
        [
            "roi_dir",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
            "all_marker_fluor_codes",
        ]
    ]
)

example_path_import: X:\abcabc\Aang_Foundation\20250808_mem_organelle
mapped example_roi_dir: /clusterfs/vast/abcabc/Aang_Foundation\20250808_mem_organelle

=== WORKING FLAT rows with roi_dir == mapped path ===
matches shape: (0, 24)

Empty DataFrame
Columns: [roi_dir, genotype_marker_fluor_codes, genotype_marker_tag_codes, treatment_plasmid_base_codes, treatment_rna_base_codes, treatment_marker_fluor_codes, treatment_marker_tag_codes, all_marker_fluor_codes]
Index: []

In [18]:
# CELL: search roi_dir by just the experiment folder name

tail = "Aang_Foundation/20250808_mem_organelle"

print("Looking for tail:", tail)
matches_tail = df_flat[df_flat["roi_dir"].astype(str).str.contains(tail.replace("\\", "/"), case=False, na=False)]

print("matches_tail shape:", matches_tail.shape)
display(
    matches_tail[
        [
            "roi_dir",
            "genotype_marker_fluor_codes",
            "genotype_marker_tag_codes",
            "treatment_plasmid_base_codes",
            "treatment_rna_base_codes",
            "treatment_marker_fluor_codes",
            "treatment_marker_tag_codes",
            "all_marker_fluor_codes",
        ]
    ].head(20)
)

Looking for tail: Aang_Foundation/20250808_mem_organelle
matches_tail shape: (21, 24)

,roi_dir,genotype_marker_fluor_codes,genotype_marker_tag_codes,treatment_plasmid_base_codes,treatment_rna_base_codes,treatment_marker_fluor_codes,treatment_marker_tag_codes,all_marker_fluor_codes
459,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
460,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
461,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
462,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
463,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
464,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
465,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
466,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
467,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
468,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
469,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
470,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
471,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
472,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
473,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
474,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
475,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
476,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
477,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada
478,/clusterfs/vast/abcabc/Aang_Foundation/2025080...,tdmChilada,2xLynk,NaN,MGCO-01,NaN,NaN,tdmChilada